### ISSUE TITLE
pytest's tests fail: ValueError: Plugin already registered (module 'tests.conftest') (caused by virtualenv's local symlinks)

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#102]
When trying to run the pytest_django tests, py.test fails/aborts:

>    E           ValueError: Plugin already registered: venv/src/pytest_django/tests/conftest.py=<module 'tests.conftest' from 'venv/src/pytest_django/tests/conftest.py'>

I have even tried it in a basic Docker image to make sure it's nothing specific to my setup.

I am using `DJANGO_SETTINGS_MODULE=tests.settings_sqlite` and pytest_django master.

Since it worked before, I am really wondering what is wrong here.

I have also tried pytest-dev (-e hg+https://bitbucket.org/hpk42/pytest@177f44412427b5060724fafe0263b35bddd91183#egg=pytest-dev).

```
% bin/py.test
========================================================================== test session starts ===========================================================================
platform linux2 -- Python 2.7.5 -- py-1.4.20 -- pytest-2.6.0.dev1
plugins: django, xdist
collected 0 items / 1 errors 

================================================================================= ERRORS =================================================================================
___________________________________________________________________________ ERROR collecting . ___________________________________________________________________________
local/lib/python2.7/site-packages/py/_path/common.py:327: in visit
>       for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
local/lib/python2.7/site-packages/py/_path/common.py:373: in gen
>               for p in self.gen(subdir):
local/lib/python2.7/site-packages/py/_path/common.py:363: in gen
>                   if p.check(dir=1) and (rec is None or rec(p))])
…/pytest/_pytest/main.py:620: in _recurse
>       ihook.pytest_collect_directory(path=path, parent=self)
…/pytest/_pytest/main.py:162: in call_matching_hooks
>       plugins = self.config._getmatchingplugins(self.fspath)
…/pytest/_pytest/config.py:680: in _getmatchingplugins
>       plugins += self._conftest.getconftestmodules(fspath)
…/pytest/_pytest/config.py:513: in getconftestmodules
>                   mod = self.importconftest(conftestpath)
…/pytest/_pytest/config.py:546: in importconftest
>               self._onimport(mod)
…/pytest/_pytest/config.py:666: in _onimportconftest
>       self.pluginmanager.consider_conftest(conftestmodule)
…/pytest/_pytest/core.py:199: in consider_conftest
>       if self.register(conftestmodule, name=conftestmodule.__file__):
…/pytest/_pytest/core.py:94: in register
>                             name, plugin, self._name2plugin))
E           ValueError: Plugin already registered: venv/src/pytest_django/tests/conftest.py=<module 'tests.conftest' from 'venv/src/pytest_django/tests/conftest.py'>
E           {'helpconfig': <module '_pytest.helpconfig' from '…/pytest/_pytest/helpconfig.pyc'>, 'pytestconfig': <_pytest.config.Config object at 0x2af56c1c6b90>, 'runner': <module '_pytest.runner' from '…/pytest/_pytest/runner.pyc'>, 'unittest': <module '_pytest.unittest' from '…/pytest/_pytest/unittest.pyc'>, 'xdist': <module 'xdist.plugin' from 'venv/src/pytest_django/local/lib/python2.7/site-packages/xdist/plugin.pyc'>, 'pastebin': <module '_pytest.pastebin' from '…/pytest/_pytest/pastebin.pyc'>, 'skipping': <module '_pytest.skipping' from '…/pytest/_pytest/skipping.pyc'>, 'genscript': <module '_pytest.genscript' from '…/pytest/_pytest/genscript.pyc'>, 'session': <Session 'pytest_django'>, 'tmpdir': <module '_pytest.tmpdir' from '…/pytest/_pytest/tmpdir.pyc'>, 'capture': <module '_pytest.capture' from '…/pytest/_pytest/capture.pyc'>, 'terminalreporter': <_pytest.terminal.TerminalReporter instance at 0x24beb90>, 'assertion': <module '_pytest.assertion' from '…/pytest/_pytest/assertion/__init__.pyc'>, 'mark': <module '_pytest.mark' from '…/pytest/_pytest/mark.pyc'>, 'terminal': <module '_pytest.terminal' from '…/pytest/_pytest/terminal.pyc'>, 'main': <module '_pytest.main' from '…/pytest/_pytest/main.pyc'>, 'nose': <module '_pytest.nose' from '…/pytest/_pytest/nose.pyc'>, '47233542048400': <_pytest.config.PytestPluginManager object at 0x2af56a7eca90>, 'python': <module '_pytest.python' from '…/pytest/_pytest/python.pyc'>, 'recwarn': <module '_pytest.recwarn' from '…/pytest/_pytest/recwarn.pyc'>, 'funcmanage': <_pytest.python.FixtureManager instance at 0x2350c68>, 'monkeypatch': <module '_pytest.monkeypatch' from '…/pytest/_pytest/monkeypatch.pyc'>, 'venv/src/pytest_django/tests/conftest.py': <module 'tests.conftest' from 'venv/src/pytest_django/tests/conftest.py'>, 'resultlog': <module '_pytest.resultlog' from '…/pytest/_pytest/resultlog.pyc'>, 'capturemanager': <_pytest.capture.CaptureManager instance at 0x1d314d0>, 'django': <module 'pytest_django.plugin' from 'venv/src/pytest_django/pytest_django/plugin.pyc'>, 'junitxml': <module '_pytest.junitxml' from '…/pytest/_pytest/junitxml.pyc'>, 'doctest': <module '_pytest.doctest' from '…/pytest/_pytest/doctest.pyc'>, 'pytester': <module '_pytest.pytester' from '…/pytest/_pytest/pytester.pyc'>, 'pdb': <module '_pytest.pdb' from '…/pytest/_pytest/pdb.pyc'>}
======================================================================== 1 error in 0.12 seconds =========================================================================
```

**Comment by ionelmc** [comment]
Just a quick question: you didn't intend to actually collect all the tests from everything installed in your virtualenv right? There's no way that something one would want, well, not in my mind :)

An easy workaround here is to just specify a path to your tests directory and not let pytest collect everything in your current working dir.

**Comment by blueyed** [comment]
@ionelmc 
I think by that time I might have wanted to try that.

I am using `testpaths` currently, or specify the paths explicitly.

**Comment by luarvik-od** [comment]
Have faced with the same problem.
C:\Users\igor.k\AppData\Local\Programs\Python\Python36\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pycharm_jb_pytest_runner.py" --path C:/Users/igor.k/.PyCharmCE2017.1/snaapy/snaapy-ui-tests/Tests/Tests_customer_dashboard
Testing started at 1:31 PM ...
Launching py.test with arguments C:/Users/igor.k/.PyCharmCE2017.1/snaapy/snaapy-ui-tests/Tests/Tests_customer_dashboard in C:\Users\igor.k.PyCharmCE2017.1\snaapy\snaapy-ui-tests\Tests\Tests_customer_dashboard
Traceback (most recent call last):
File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pycharm_jb_pytest_runner.py", line 27, in 
pytest.main(sys.argv[1:], plugins_to_load)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\config.py", line 49, in main
config = _prepareconfig(args, plugins)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\config.py", line 158, in _prepareconfig
pluginmanager=pluginmanager, args=args)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 745, in call
return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 334, in 
_MultiCall(methods, kwargs, hook.spec_opts).execute()
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 613, in execute
return _wrapped_call(hook_impl.function(*args), self.execute)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 250, in _wrapped_call
wrap_controller.send(call_outcome)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\helpconfig.py", line 34, in pytest_cmdline_parse
config = outcome.get_result()
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 279, in get_result
raise ex[1].with_traceback(ex[2])
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 265, in init
self.result = func()
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 614, in execute
res = hook_impl.function(*args)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\config.py", line 928, in pytest_cmdline_parse
self.parse(args)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\config.py", line 1086, in parse
self._preparse(args, addopts=addopts)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\config.py", line 1048, in _preparse
self.pluginmanager.load_setuptools_entrypoints(entrypoint_name)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 516, in load_setuptools_entrypoints
self.register(plugin, name=ep.name)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\config.py", line 252, in register
ret = super(PytestPluginManager, self).register(plugin, name)
File "C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages_pytest\vendored_packages\pluggy.py", line 351, in register
(plugin_name, plugin, self._name2plugin))
ValueError: Plugin already registered: allure_pytest=<module 'allure.pytest_plugin' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\allure\pytest_plugin.py'>
{'2584530579808': <_pytest.config.PytestPluginManager object at 0x00000259C206F160>, 'pytestconfig': <_pytest.config.Config object at 0x00000259C20D6358>, 'mark': <module '_pytest.mark' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\mark.py'>, 'main': <module '_pytest.main' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\main.py'>, 'terminal': <module '_pytest.terminal' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\terminal.py'>, 'runner': <module '_pytest.runner' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\runner.py'>, 'python': <module '_pytest.python' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\python.py'>, 'fixtures': <module '_pytest.fixtures' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\fixtures.py'>, 'debugging': <module '_pytest.debugging' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\debugging.py'>, 'unittest': <module '_pytest.unittest' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\unittest.py'>, 'capture': <module '_pytest.capture' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\capture.py'>, 'skipping': <module '_pytest.skipping' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\skipping.py'>, 'tmpdir': <module '_pytest.tmpdir' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\tmpdir.py'>, 'monkeypatch': <module '_pytest.monkeypatch' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\monkeypatch.py'>, 'recwarn': <module '_pytest.recwarn' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\recwarn.py'>, 'pastebin': <module '_pytest.pastebin' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\pastebin.py'>, 'helpconfig': <module '_pytest.helpconfig' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\helpconfig.py'>, 'nose': <module '_pytest.nose' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\nose.py'>, 'assertion': <module '_pytest.assertion' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\assertion\init.py'>, 'junitxml': <module '_pytest.junitxml' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\junitxml.py'>, 'resultlog': <module '_pytest.resultlog' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\resultlog.py'>, 'doctest': <module '_pytest.doctest' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\doctest.py'>, 'cacheprovider': <module '_pytest.cacheprovider' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\cacheprovider.py'>, 'freeze_support': <module '_pytest.freeze_support' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\freeze_support.py'>, 'setuponly': <module '_pytest.setuponly' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\setuponly.py'>, 'setupplan': <module '_pytest.setupplan' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\setupplan.py'>, 'warnings': <module '_pytest.warnings' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\_pytest\warnings.py'>, 'teamcity.pytest_plugin': <module 'teamcity.pytest_plugin' from 'C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.2\helpers\pycharm\teamcity\pytest_plugin.py'>, 'allure_adaptor': <module 'allure.pytest_plugin' from 'C:\Users\igor.k\AppData\Local\Programs\Python\Python36\lib\site-packages\allure\pytest_plugin.py'>}

Process finished with exit code 1
Empty test suite.

Please, advice

**Comment by dinaledvina** [comment]
Hi Guys! How to resolve this error:

================================================================= test session starts ==================================================================
platform darwin -- Python 3.9.6, pytest-7.2.2, pluggy-1.0.0
rootdir: /Users/dinaledvin, configfile: pytest.ini
plugins: allure-pytest-2.13.1, html-3.2.0, metadata-2.0.4
collected 0 items / 1 error                                                                                                                            

======================================================================== ERRORS ========================================================================
____________________________________________________________ ERROR collecting test session _____________________________________________________________
Library/Python/3.9/lib/python/site-packages/pluggy/_manager.py:115: in register
    hook._maybe_apply_history(hookimpl)
Library/Python/3.9/lib/python/site-packages/pluggy/_hooks.py:300: in _maybe_apply_history
    res = self._hookexec(self.name, [method], kwargs, False)
Library/Python/3.9/lib/python/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
Downloads/pytest-dev-pytest-1ae778f/testing/example_scripts/conftest_usageerror/conftest.py:4: in pytest_configure
    raise pytest.UsageError("hello")
E   _pytest.config.exceptions.UsageError: hello
=============================================================== short test summary info ================================================================
ERROR  - _pytest.config.exceptions.UsageError: hello
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================== 1 error in 4.08s ===================================================================
Dinas-MBP-2:~ dinaledvin$
