### ISSUE TITLE
mocked settings attribute in pytest does not work with django post_save signals

### ISSUE THREAD

**Issue by ssandr1kka** [pytest-dev/pytest-django#1026]
So guys, I am using pytest

I have checked: https://stackoverflow.com/questions/62642825/how-to-mock-django-settings-attributes-in-pytest-django and https://pytest-django.readthedocs.io/en/latest/helpers.html#id4 . The docs mention that using following approach we can alter settings attributes:
```
def test_with_specific_settings(settings):
    settings.USE_TZ = True
    assert settings.USE_TZ
```
Thus my test class looks like:
```
@pytest.mark.django_db
class TestCase:
    @pytest.fixture(autouse=True)
    def _setup_endpoint(self, test_user, settings) -> None:
        settings.SUSPEND_SIGNALS = True
        print(settings.SUSPEND_SIGNALS) --> returns True
        self.endpoint = endpoint setup

    def test_create(self, test_profile) -> None:
        response = self.endpoint.post(payload={})
        assert response.status_code == 401
```
test_profile triggers a signal where I check again
```
            print(settings.SUSPEND_SIGNALS) --> returns False
```
Why do I get different results? How do I make sure that second print statement is also True? I appreciate your help guys

**Comment by mgax** [comment]
`test_profile` is a fixture? Maybe it's applied before the `_setup_endpoint` fixture?

**Comment by ssandr1kka** [comment]
`test_profile` is my fixture, however here is the different piece of code that excludes the usage of any fixtures

```
@pytest.mark.django_db
class TestCreatePaymentIntent:
    @pytest.fixture(autouse=True)
    def _setup_endpoint(self, settings) -> None:
        settings.SUSPEND_SIGNALS = True
        self.endpoint = NinjaEndpoint(base_url="/api" + CREATE_PAYMENT_INTENT_URL)

    def test_create_profile_payment_intent_anonymous_user(self, settings) -> None:
        print(settings.SUSPEND_SIGNALS)  --> returns True
        test_profile: ProfileModel = create_test_profile()
        self.endpoint.set_user(test_profile.user)
        response = self.endpoint.post(payload={})
        assert response.status_code == 401

```
```
print(settings.SUSPEND_SIGNALS) --> Still returns False
```

**Comment by ssandr1kka** [comment]
`from django.confs import settings` 
Actually no bug here, it was issue from my side, I was not importing settings as I should have had.
