### ISSUE TITLE
Settings with stdout output (print) malforms Pytest JSON output

### ISSUE THREAD

**Issue by noamsto** [pytest-dev/pytest-django#1031]
Hi,

I'm using pytest with Visual Studio Code and since they started using Pytest JSON output it fails to run properly on our project.
The reason is we have prints on our Django settings files (bad practice, but it's already there) and it malforms the JSON output. 
In any-case I think Pytest output shouldn't be effected by stdout mishaps that can happen while this plugin does it's work.

I've already thought of quite an easy way to solve it, simply redirect all `django.setup()` output to `stderr`.

i.e.:
```python
@contextmanager
def redirect_stdout_to_stderr():
    orig_stdout = sys.stdout
    sys.stdout = sys.stderr
    yield
    sys.stdout = orig_stdout
```

and wherever we do `django.setup()`:
```python
with redirect_stdout_to_stderr():
    django.setup()
```

Then we can still see the prints output and won't hurt strict format outputs like JSON.

How does it sound?
Should I create a PR?

**Comment by mgax** [comment]
@noamsto Pytest already [captures stdout by default](https://docs.pytest.org/en/7.1.x/how-to/capture-stdout-stderr.html#default-stdout-stderr-stdin-capturing-behaviour), but it can be disabled by configuration or command-line flags. Maybe you're disabling capture somehow?

**Comment by noamsto** [comment]
Wow what a poor mistake...
I intended to write this to Pylint-Django plugin :man_facepalming: 
I blame it on the lack of sleep cause of a childbirth (man the boy is only 3 weeks and I start blaming him with stuff).

All good with Pytest plugin :muscle: 

Sorry for the mistake, closing this.
