### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by mateenkasim** [pytest-dev/pytest-django#1048]
Is there a timeline on the next release?

When I saw that the last release on PyPI was in 2021, I thought this package was dead, but I'm surprised to see that there's been plenty of activity since then. This package seems to be the standard for using pytest with Django, but I don't want to dive into it if won't receive more updates. Hopefully, the release schedule can get back on track this year, perhaps before Django 4.2 comes out in April. Thanks for any input you might have!

**Comment by bluetech** [comment]
> When I saw that the last release on PyPI was in 2021, I thought this package was dead, but I'm surprised to see that there's been plenty of activity since then.

There is no reason to do a release, so there hasn't been one.

> This package seems to be the standard for using pytest with Django, but I don't want to dive into it if won't receive more updates.

The core of pytest-django is pytest and `django.test`. The plugin itself is glue. As long as the glue works, there is not much to update.

> Hopefully, the release schedule can get back on track this year, perhaps before Django 4.2 comes out in April

The latest release of pytest-django works well with Django 4.2.

**Comment by mateenkasim** [comment]
Got it, thanks for clearing that up. The "glue" point makes sense. Closing!

**Comment by simkimsia** [comment]
I was googling about this as well. This would have been good as FAQ on readme
