### ISSUE TITLE
`SimpleTestCase` triggers database migrations

### ISSUE THREAD

**Issue by flaeppe** [pytest-dev/pytest-django#1049]
The default implementation of `SimpleTestCase` disables database queries per default, which is why I'm thinking that migrating the database could conditionally happen depending on the value of `SimpleTestCase.databases`?

> [SimpleTestCase](https://docs.djangoproject.com/en/4.1/topics/testing/tools/#django.test.SimpleTestCase) disallows database queries by default. This helps to avoid executing write queries which will affect other tests since each SimpleTestCase test isn’t run in a transaction. If you aren’t concerned about this problem, you can disable this behavior by setting the databases class attribute to '__all__' on your test class.

Ref: https://docs.djangoproject.com/en/4.1/topics/testing/tools/#django.test.SimpleTestCase.databases

**Comment by marianobianchi** [comment]
I'm having the same issue. It will be great to have this fixed because sometimes the difference in testing times between pytest and django tests are big because of this (i.e: django tests take 80s to finish and pytest tests take 145s)
