### ISSUE TITLE
Do common db setup between tests once

### ISSUE THREAD

**Issue by alvinchow86** [pytest-dev/pytest-django#105]
It would be useful if I could do some common database setup that's shared between tests (like loading some large fixture data or something), just once for the test run rather than for every test, for faster performance. The test would still be wrapped in a transaction, so any db changes in tests would be rolled back to the original state. 

However this doesn't seem possible in pytest_django, since the `db` fixture is only function scoped, whereas I might want to do this database setup on a module or session scope.

**Comment by rbiersbach** [comment]
We also have a problem with this as we are using parameterize a lot for read-only access. 
We have a workaround but that just feels super awkward compared to the scopes which are intended for this purpose originally.

**Comment by bluetech** [comment]
We are having some overlapping discussion on this in #514, I'll close this one in favor of that.
