### ISSUE TITLE
FAIL_INVALID_TEMPLATE_VARS interferes with {% if model.one_to_one_field %}

### ISSUE THREAD

**Issue by voidus** [pytest-dev/pytest-django#1059]
Assuming I have the following model:

```python
class Person(models.Model):
  pass

class Purpose(models.Model):
  person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name="purpose")
```

and the following template (assuming `person` is an instance of `Person` with no associated `Purpose`

```jinja2
        {% if person.purpose %}
            yes
        {% else %}
            no
        {% endif %}
```

Expected: "no"
Actual: "yes" if FAIL_INVALID_TEMPLATE_VARS is true, "no" otherwise

As far as I can see, person.purpose raises `RelatedObjectDoesNotExist`, which is then caught by django and converted into the `string_if_invalid`, which is set to an `InvalidVarException` instance.
The `IfNode` then uses `if match:` to determine whether to render the content, with match being our `InvalidVarException`.

Please let me know if I'm holding it wrong, but especially since this deviates from the regular behavior it looks like a bug to me

**Comment by voidus** [comment]
I was indeed holding it wrong, it should have been `{% if person.purpose.exists %}...`

**Comment by xavfernandez** [comment]
> I was indeed holding it wrong, it should have been {% if person.purpose.exists %}...

I don't see how it would work and agree with your first understanding: 

> As far as I can see, person.purpose raises `RelatedObjectDoesNotExist`, which is then caught by django and converted into the `string_if_invalid`, which is set to an `InvalidVarException` instance. The `IfNode` then uses `if match:` to determine whether to render the content, with match being our `InvalidVarException`.
> 
> Please let me know if I'm holding it wrong, but especially since this deviates from the regular behavior it looks like a bug to me

**Comment by voidus** [comment]
I think I'm still with my not-a-bug understanding, but this is super confusing so I'll elaborate a bit and maybe we can figure our what's going on

We have a one-to-many relationship here, with each purpose having one person and one person having zero or more purposes. Sorry I I chose a confusing example.
I made it worse by setting `related_name="purpose"`, so in this comment, I'll stick with the django default, which is `purpose_set`

The template is now:

```
        {% if person.purpose_set %}
            yes
        {% else %}
            no
        {% endif %}
```

and person.purpose_set resolves to a `RelatedManager` on which you can call stuff like `get`, `filter`, and `exists`. Since the `RelatedManager` is not falsy, it prints yes.

Things would be different when going the other direction. I don't have the setup to try that right now, but `purpose.person` should be a `Person` immediately. Not sure if there would be an issue with that case.

What do you think?

**Comment by adamchainz** [comment]
The underlying `string_if_invalid` Django template option can break templates in all manner of ways, which I blogged about last year: https://adamj.eu/tech/2023/08/09/django-perils-string-if-invalid/ . Using the pytest-django feature comes with the same perils. I don’t think pytest-django should try and correct this, instead I think we can improve things upstream in Django (maybe by replacing the feature with Jinja-like missing-variable handling).
