### ISSUE TITLE
Intercept connection attempt to the database already? (without django_db mark)

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#107]
I have noticed that the tests fail when there is no database.

They expect `pytest.fail.Exception` (thrown because of the missing mark):

    def test_noaccess():
        with pytest.raises(pytest.fail.Exception):
            Item.objects.create(name='spam')
        with pytest.raises(pytest.fail.Exception):
            Item.objects.count()

I wonder if pytest_django should have interrupted the database access earlier already, preventing Django from connecting to the db.

Or is this by design, so that you are aware of any connection problems?
In that case this should be documented with the tests somehow, and maybe these tests could be skipped?

    _____________________________________________________________________________ test_noaccess ______________________________________________________________________________
    tests/test_database.py:37: in test_noaccess
    >           Item.objects.create(name='spam')
    lib/python2.7/site-packages/django/db/models/manager.py:157: in create
    >       return self.get_queryset().create(**kwargs)
    lib/python2.7/site-packages/django/db/models/query.py:322: in create
    >       obj.save(force_insert=True, using=self.db)
    lib/python2.7/site-packages/django/db/models/base.py:545: in save
    >                      force_update=force_update, update_fields=update_fields)
    lib/python2.7/site-packages/django/db/models/base.py:570: in save_base
    >       with transaction.commit_on_success_unless_managed(using=using, savepoint=False):
    lib/python2.7/site-packages/django/db/transaction.py:532: in commit_on_success_unless_managed
    >       if connection.get_autocommit() or connection.in_atomic_block:
    lib/python2.7/site-packages/django/db/backends/__init__.py:331: in get_autocommit
    >       self.ensure_connection()
    lib/python2.7/site-packages/django/db/backends/__init__.py:127: in ensure_connection
    >               self.connect()
    lib/python2.7/site-packages/django/db/utils.py:99: in __exit__
    >               six.reraise(dj_exc_type, dj_exc_value, traceback)
    lib/python2.7/site-packages/django/db/backends/__init__.py:127: in ensure_connection
    >               self.connect()
    lib/python2.7/site-packages/django/db/backends/__init__.py:115: in connect
    >       self.connection = self.get_new_connection(conn_params)
    lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py:114: in get_new_connection
    >       return Database.connect(**conn_params)
    lib/python2.7/site-packages/psycopg2/__init__.py:164: in connect
    >       conn = _connect(dsn, connection_factory=connection_factory, async=async)
    E       OperationalError: FATAL:  database "pytest_django" does not exist
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by pelme** [comment]
This is fixed now with the new database blocker which acts on the connection level. :)
