### ISSUE TITLE
Request: supporting progress percentage like vanilla `pytest`

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pytest-django#1072]
Vanilla `pytest` supports progress percentage on the right:

<img src="https://github.com/pytest-dev/pytest-django/assets/8990777/a38453f1-712b-4dbd-9b44-34c2aa07e6ff" alt="screenshot of pytest progress percentage" width="55">

Can `pytest-django` support this progress percentage behavior too?

The idea is when one runs `python -m manage test --parallel --verbosity=3`, a progress percentage shows up on the right

**Comment by mgax** [comment]
I'm pretty sure `pytest-django` supports this format, I use it in my projects and the percentage shows up. Perhaps it's because of the way you invoke tests. Have you tried running `pytest` instead of `python -m manage test`?

**Comment by jamesbraza** [comment]
You are right, it's actually supported.  I didn't realize I needed to switch from `python -m manage test` to `pytest` to actually use `pytest-django`, apologies for the user error.

Progress monitoring is actually present, closing this as resolved 👍 thanks!
