### ISSUE TITLE
A fixture for the project's `urlpatterns`

### ISSUE THREAD

**Issue by paduszyk** [pytest-dev/pytest-django#1116]
The plugin provides a decent collection of fixtures. 

What would you say about a new one, yielding a list of the project's URL patterns:

```python
from importlib import import_module

@pytest.fixture()
def urlpatterns(settings):
    """Yield the project's URL patterns and restore them after each test."""
    # Import the root URLconf module.
    urlconf = import_module(settings.ROOT_URLCONF)

    # Copy the project's URL patterns.
    urlpatterns_copy = urlconf.urlpatterns.copy()

    # Yield.
    yield urlconf.urlpatterns

    # Restore.
    urlconf.urlpatterns = urlpatterns_copy
```

I think this might be useful for testing apps that interact with the URLconf.

If the repo's community finds this idea interesting, I will implement and test it ASAP.

**Comment by adamchainz** [comment]
This seems too niche to me. You already have an implementation you can copy into projects as needed.
