### ISSUE TITLE
apps.ready() doesn't get called

### ISSUE THREAD

**Issue by vt-rcheng** [pytest-dev/pytest-django#1122]
this issues is a follow up to #204

I am using pytest-django to test, but the apps.ready() are not being called. It is where I add signals to the ORM models and so my tests are breaking.

If I start the service using manage.py, the apps.ready does get called, but if I run pytest it does not work.
The solution in #204  does not help. I am using the latest pytest-django 4.8.0 and and Django 5.0.4 which no longer requires default_app_config (the solution in #204).

when I print out

`django.apps.apps.ready`

in https://github.com/pytest-dev/pytest-django/blob/11f613da77b5bc22d44eaa8c82a0fda427f091cb/pytest_django/plugin.py#L223

The apps are already ready. But the apps.ready() was not called.

I am really confused what I am doing wrong. Thank you

**Comment by vt-rcheng** [comment]
nevermind, it was simply not printing output because of logging setup

**Comment by adamchainz** [comment]
Thank you for reporting back your finding and closing the issue. Test setups are complex, it’s easy to miss something like why output doesn't display!
