### ISSUE TITLE
Is Django 2.2 supported in latest or not?

### ISSUE THREAD

**Issue by Faithfinder** [pytest-dev/pytest-django#1124]
Release notes for [4.5.0](https://pytest-django.readthedocs.io/en/latest/changelog.html#v4-5-0-2021-12-01) say that Django 2.2 is still supported officially, however Readme doesn't list it and no later release notes mention it was dropped.

**Comment by stefan6419846** [comment]
According to the commits, supports has been dropped in version 4.6.0: https://github.com/pytest-dev/pytest-django/commit/fba51531f067a985ec6b6be4aec9a2ed5766d69c
