### ISSUE TITLE
Github Actions are failing on new PRs.

### ISSUE THREAD

**Issue by pzarfos** [pytest-dev/pytest-django#1133]
The Github Actions have been failing on new PRs.
They are failing on the "codecov" step.

Did the Codecov API token expire?

see `secrets.CODECOV_TOKEN` in codecov.yml
- https://github.com/pytest-dev/pytest-django/blob/master/.github/workflows/main.yml#L62

The error message in the action log says it is being rate limited:
```
There was an error running the uploader: Error uploading to https://codecov.io: 
Error: There was an error fetching the storage URL during POST: 429 - 
{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 305s.', code='throttled')}

Error: Codecov: Failed to properly upload: 
The process '/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255
```

Can one of the maintainers check if the Codecov API token `secrets.CODECOV_TOKEN` is still valid?

**Comment by webknjaz** [comment]
@bluetech FYI, many projects ended up storing the token as clear text, in the config. This helps with the flakiness in PRs.
