### ISSUE TITLE
Improve the settings fixture

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest-django#136]
Django has a decorator that is called `override_settings` and `modify_settings` (located in https://github.com/django/django/blob/master/django/test/utils.py). Apart from just changing the value in `django.conf.settings`, `override_settings` will also send a signal for changed settings.

Our settings fixture should make use of this these methods internally to make settings changes in a more reliable way.
#46 is related to this.

**Comment by syphar** [comment]
@pelme anything happening here? Did you have any problems with the implementation in the commit? 

We just stumbled on this problem. We're also happy takeover any PR and fix

**Comment by aaugustin** [comment]
Yes, that would be nice.

**Comment by mdentremont** [comment]
I'm noticing that after updating to Django 1.10, the `django.templatetags.static` has been changed so that it could end up making use of cached properties, meaning modifications to things like `STATIC_URL` might be missed (if `static` has already once in a previous test)

**Comment by aaugustin** [comment]
Woohooo! Thanks!

**Comment by pelme** [comment]
It's very nice that we finally have a solution for this! :) I will put out a new release as soon as #417 is fixed.
