### ISSUE TITLE
Warning/Exception if a test commits something without transactional_db fixture

### ISSUE THREAD

**Issue by jarus** [pytest-dev/pytest-django#164]
Hi,

I had sometimes the following problem. One test commits his transaction without the transactional_db fixture. This test also pass but the next test is going to fail because the database isn't anymore in the expected state. Also it can be very difficult and time expensive to find the "bad" test which commits something.

I would recommend to raise a exception if a transaction is committed inside of test which doesn't have the transactional_db fixture like the exception if you use the database without the fixture or mark.

Best regards
Christoph

**Comment by pelme** [comment]
This issue should be fixed in the latest master. To ensure tests don't touch the database, the blocking is now done on the connection level rather than the cursor level.

Please give the latest master a try and reopen this issue if the problems persists!
