### ISSUE TITLE
Decorate pytest_load_initial_conftests hook with @pytest.mark.trylast

### ISSUE THREAD

**Issue by mkemmerling** [pytest-dev/pytest-django#186]
... or convince the _pytest-cov_ maintainer to decorate their _pytest_load_initial_conftests_ hook with _@pytest.mark.tryfirst_.

This issue refers to issue #175 (and https://github.com/schlamar/pytest-cov/issues/19) which did *not* solve the problem for me that _pytest_cov_ fails to cover module level code.

_pytest_django_ 2.7.0 ans _pytest_cov_ 1.8.0 both use a _pytest_load_initial_conftests_ hook to setup Django and to start coverage measurement, respectively. But it is important that the hook in _pytest_cov_ is executed _before_ the hook in _pytest_django_. So the question is, which of the two hooks is executed first. I found that the hook in _pytest_django_ is executed first, therefore coverage measurement is still broken. I suppose that this is platform dependant.

In more detail:

As usual I installed _pytest_django_ and _pytest_cov_ via pip in a virtual environment. pytest loads both plugins via their setuptools entry points. The order in which they are loaded depends on the scannning of the installed  packages in the virtual environment. pytest's _PluginManager_ uses _setuptools iter_entry_points()_ function to iterate over all entry points. https://pythonhosted.org/setuptools/pkg_resources.html#convenience-api clarifies that "entry points are yielded from the active distributions in the order that the distributions appear on sys.path", but it does not say anything about the order of entry points from packages living in the same directory. Poking a little bit around I found that - at least under Python 3.4 - the packages seem to be looked up with _os.listdir()_ which returns directory entries in arbitrary order. In my case _pytest_cov_ was registered _before_ _pytest_django_, its _pytest_load_initial_conftests_ hook therefore executed _after_ the one in _pytest_django_ (the order is reversed by _MultiCall.execute()_ which pops the hooks to be executed from the list of collected hooks).

Fortunately pytest allows to determine the order in which hooks are executed in some way with the _@pytest.mark.tryfirst_ and _@pytest.mark.trylast_ decorators (see http://pytest.org/latest/example/markers.html#registering-markers). Decorating the _pytest_load_initial_conftests_ hook in _pytest_django_ with the _@pytest.mark.trylast_ decorator ensures that Django is setup after coverage measurement has been started.

Note that the _pytest_load_initial_conftests_ hook in _pytest_cov_ is decorated with an invalid _@pytest.mark.try_last_ decorator (note the underscore) which has no effect. Considering the fact that coverage measurement should probably always be started as early as possible the better solution might be to decorate the _pytest_load_initial_conftests_ hook in _pytest_cov_  with the _@pytest.mark.tryfirst_ decorator.

Sorry for this rather long posting ;-)

**Comment by pelme** [comment]
Ok, good to see that it was fixed. :) I'm closing this issue now!
