### ISSUE TITLE
assertNumQueries analogue

### ISSUE THREAD

**Issue by l0kix2** [pytest-dev/pytest-django#187]
In Django TransactionTestCase we have useful method `assertNumQueries` https://docs.djangoproject.com/en/1.7/topics/testing/tools/#django.test.TransactionTestCase.assertNumQueries. 
Can we do something like that in pytest-django or maybe it is somewhere and i missed it?

**Comment by pelme** [comment]
#97 should solve this. I have a hack that I use internally that you might find useful in the meantime:
https://gist.github.com/pelme/58d5f67cbb35b34e3c20

**Comment by pelme** [comment]
Closing this issue since it is covered in #97.

**Comment by l0kix2** [comment]
Didn't understand #97 solution and where it was described, but thanks for snippet.

**Comment by blueyed** [comment]
It points to the WIP at https://github.com/pytest-dev/pytest-django/pull/232.

But regarding this issue, it is available as a `django_assert_num_queries` fixture (via #387).
It has not been released yet though.
