### ISSUE TITLE
Django 1.8 Support

### ISSUE THREAD

**Issue by DavidMuller** [pytest-dev/pytest-django#189]
Do you guys have a preliminary plan for supporting [Django 1.8](https://code.djangoproject.com/wiki/Version1.8Roadmap)?  

pytest-django is throwing:
```python
 Failed: Database access not allowed, use the "django_db" mark to enable
``` 
all over the place for Django 1.8 builds of Django Rest Framework (see [failed build example](https://travis-ci.org/tomchristie/django-rest-framework/jobs/45205560)).

I was also having trouble getting even a simple project going (see [repository](https://github.com/DavidMuller/pytest_django_failure)):
```python
from django.test import TestCase

class FirstTestClass(TestCase):
    def test_one(self):
        self.assertEquals(0, 0)
```

```python
python manage.py test

Creating test database for alias 'default'...
.
----------------------------------------------------------------------
Ran 1 test in 0.000s
```

Same test fails with `py.test`:
```python
../../Envs/failure/lib/python2.7/site-packages/django/db/backends/__init__.py:151: in _cursor
    return self.create_cursor()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x104f24ad0>

    def create_cursor(self):
>       return self.connection.cursor(factory=SQLiteCursorWrapper)
E       ProgrammingError: Cannot operate on a closed database.

../../Envs/failure/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py:425: ProgrammingError
================================================================== 1 error in 0.17 seconds ===================================================================

```

I believe the Django 1.8 feature freeze is Jan 12th.

**Comment by pelme** [comment]
`setUpClass` should now be properly supported, but there are a bunch of tricky things involved here and I would really appreciate if you could give the current master a try before I put out a new version.

I also stumbled upon a Django bug (not directly related to this issue).
#191 / https://code.djangoproject.com/ticket/24069 A review of that issue/patch would be helpful :) 

There are also another test failure for the latest Django master that I hope can fix soon!

**Comment by pelme** [comment]
Ok, all tests are now passing, if you could give this a try with your 1.8 projects that would be really helpful.

Here is a one-liner to install the latest version:
```
pip install -e git+https://github.com/pytest-dev/pytest-django.git#egg=pytest-django
```

**Comment by DavidMuller** [comment]
Wow, thanks for such a quick fix. I am not near my machine at the moment, but will be there later today and can try it out.

**Comment by DavidMuller** [comment]
I can confirm that the dirt simple Django 1.8 app that I referenced in the initial post of this thread now works ([repo](https://github.com/DavidMuller/pytest_django_failure)).

A build of Django Rest Framework master with Django 1.8 also appears to be free of `pytest-django` related errors.

:+1:

**Comment by pelme** [comment]
Good to hear! I plan to merge a couple of other changes and have a new release today or tomorrow.
