### ISSUE TITLE
app.ready() doesn't get called

### ISSUE THREAD

**Issue by rokcarl** [pytest-dev/pytest-django#204]
I have some initialization code in the [application](https://docs.djangoproject.com/en/1.7/ref/applications/)'s `ready` method, but this code does not get called when I run `py.test`.

**Comment by pelme** [comment]
Hmm, that should work and there is a test in pytest-django that checks this:
https://github.com/pytest-dev/pytest-django/blob/master/tests/test_django_settings_module.py#L229

Can you give some more details? Does the ready method get called when used with runserver? Are INSTALLED_APPS properly configured in your test environment?

**Comment by blueyed** [comment]
@rokcarl 
Which version of Django are you using?

There appears to be a problem with master, with exactly the test @pelme mentions: https://travis-ci.org/pytest-dev/pytest-django/jobs/50237910.

**Comment by rokcarl** [comment]
* _Version:_ `django.VERSION == (1, 7, 1, 'final', 0)`.
* _Called with runserver?_ Yes, actually it's run two times.
* _Installed apps?_ This is the part I'm not totally sure about, I was debugging this yesterday too and it seemed to me it's not picking it up, though I've tried all the methods, currently I have this [pytest.ini](https://gist.github.com/rokcarl/70b71e79e96e3d41c732) in root.

**Comment by pelme** [comment]
`ready()` should really work, and there are tests that (at least in theory :-)) should verify this. I'm closing this issue for now, please reopen it again if the problem still persists with the current version of pytest-django!

**Comment by denolehov** [comment]
whoever stumbles on this:
Make sure that `default_app_config` is set, otherwise django will use vanilla `AppConfig` for your application.

Docs: https://docs.djangoproject.com/en/3.0/ref/applications/#configuring-applications
