### ISSUE TITLE
"(1_7.W001) MIDDLEWARE_CLASSES is not set" warning with Django 1.7

### ISSUE THREAD

**Issue by adriaant** [pytest-dev/pytest-django#210]
If I use conftest.py with contents:
```
import os
from django.conf import settings
from config import unittest as test_settings

def pytest_configure():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.unittest')
    settings.configure(default_settings=test_settings)
```

Then running `py.test -s` shows a lot of "(1_7.W001) MIDDLEWARE_CLASSES is not set" even though MIDDLEWARE_CLASSES is set (verified with a print statement). 

If I use pytest.ini instead with contents:
```
[pytest]
DJANGO_SETTINGS_MODULE=config.unittest
```
The warnings disappear. 

According to documentation both versions of setting up testing should work. 

This is with Django 1.7.4 and pytest-django 2.8.0.

**Comment by pelme** [comment]
```
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.unittest')
```

or

```
settings.configure(default_settings=test_settings)
```

should be enough in `pytest_configure`. (Either the settings are configured later by pytest-django with the env-var, or you do it by yourself with `settings.configure(...)`. Do the error still happen when you only use one of them?

Could you give the latest master a try, there is a change affects how settings are being configured in `pytest_configure`.

**Comment by pelme** [comment]
I'm closing this now, please reopen it if this is still an issue with the current releases.
