### ISSUE TITLE
How to test a custom decorator

### ISSUE THREAD

**Issue by g3rd** [pytest-dev/pytest-django#211]
Is it possible to test a custom decorator with pytest / pytest-django?

(If I can get pointed in the right direction, I'll gladly open a pull request to add to the docs)

**Comment by cheif** [comment]
Hi, since a decorator is just a regular function taking a function (or class) as a input there should be no problem to test it that I can see at least.
```python
def decorate(f):
    f.decorated = True
    return f


def test_decorate():
    @decorate
    def mock_fun():
        return True
    assert mock_fun.decorated is True
```

Does this cover your case, or could you give a more through explanation of your specific case?

**Comment by pelme** [comment]
As @cheif points out decorators is a general python concept and there is nothing in pytest/pytest-django that specifically helps with testing a decorator.

I am closing this issue now, please provide some more specifics/examples on what kinds of decorators you are trying to test and we may be able to point you in the right direction.
