### ISSUE TITLE
Why settings.TEST_RUNNER is ignored?

### ISSUE THREAD

**Issue by st4lk** [pytest-dev/pytest-django#215]
`DjangoTestRunner` (either `DiscoverRunner`, either `DjangoTestSuiteRunner`) is always used, according to [compat.py](https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/compat.py), ignoring `settings.TEST_RUNNER`. Why?
I think it will be useful to have possibility to set custom runner.
I can work for pull request, but maybe it is a feature of pytest-django?

**Comment by blueyed** [comment]
I think it's an oversight to not look at the setting, but am not sure.  There's not mentioning of `TEST_RUNNER` in pytest-django's history.

I pull request for this would be nice.

**Comment by st4lk** [comment]
Looks like it was misunderstanding from my side. I wanted to override method `setup_test_environment` of runner to do some actions before running the test. But pytest-django don't use django's runner in fact. As i understand, better way to do it is to implement a pytest plugin with `pytest_runtest_setup` hook.
