### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by leebrooks0** [pytest-dev/pytest-django#226]
I just setup pytest and am running 2 tests that assert x == y.
However they take 8 seconds to run?

```2 failed in 7.97 seconds```

Is this normal? The first test takes 8s and the second is more or less immediate.

**Comment by leebrooks0** [comment]
Forgot to mention they are db tests (proving that I can work with the db...).
howeever with the regular django test runner I was running 80 tests in this time?

**Comment by santagada** [comment]
have you tried running it with --reuse-db twice? pytest-django always create the database which might be what is slowing down your test run.

**Comment by leebrooks0** [comment]
Thanks, that was the issue, the tests are now running in 0.26s
