### ISSUE TITLE
why DEBUG is hardcoded to False?

### ISSUE THREAD

**Issue by bubenkoff** [pytest-dev/pytest-django#228]
Hi

https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/plugin.py#L239

this looks not too flexible
I tried a lot of things before i found this hardcode - i needed to understand why my liveserver fails, and it returned just standard 500 instead of debug page, and debug is set to True in my test settings
So i think this hardcode should be removed to respect test settings

**Comment by blueyed** [comment]
IIRC the setup with Django's testrunner is also False, to reflect what would be used in production, but I am not certain.

:+1: for a way to configure/override this.

**Comment by bubenkoff** [comment]
ok i'll prepare PR

**Comment by birdsarah** [comment]
Is this fixed #231 was reverted. This option would be really useful for me.

**Comment by blueyed** [comment]
@birdsarah 
Thanks for bringing this up.
You could pickup #231 and adjust it according to the feedback (double negation IIRC) and submit is as a new PR, since @bubenkoff appears to have forgotten about it.

**Comment by bubenkoff** [comment]
@blueyed i didn't forget, but don't have time and honestly motivation ATM :)

**Comment by blueyed** [comment]
@bubenkoff 
Fair enough and thanks for letting us now. That's what I've thought.. :)
Given your existing contribution it should be easy for somebody else to pick it up from there.

@birdsarah 
Do you think you can do that?

**Comment by birdsarah** [comment]
yes, but i've got other contributions that i'm behind on on other projects, so it has to go to the bottom of the stack.
