### ISSUE TITLE
Improve failure when a database access happens from unittest.TestCase

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#234]
From https://github.com/pytest-dev/pytest-django/pull/197#issuecomment-71329313

> Regarding the error message about the marker, we could probably improve the failure when a database access happens from a unittest.TestCase subclass to instruct the user to subclass from django.test.TestCase instead.

Should this then also happen for access through `setUpClass`, or should this behavior be left unchanged?

**Comment by pelme** [comment]
I have started to create a test for this in https://github.com/pelme/pytest_django/compare/master...unittest2

**Comment by blueyed** [comment]
Assuming this to be fixed/addressed.
