### ISSUE TITLE
py.test 2 times slower than manage.py test

### ISSUE THREAD

**Issue by Pradeek** [pytest-dev/pytest-django#239]
I installed py.test on a codebase with 111 tests, where most of them do access the database. They are all using Django's TestCase class. Running `python manage.py test` takes around 4 seconds where `py.test` averages around 9 seconds for the same tests. I know things can be further optimised by using fixtures, but why is there such a disparity on the default case? I am not using keepdb on both django and py.test

**Comment by blueyed** [comment]
Test collection might be an issue, e.g. when py.test scans your whole virtualenv etc.
Try invoking `py.test` for a specific `tests` dir, or file with tests, and compare that to `manage.py test`.

**Comment by Pradeek** [comment]
I don't think so. Both tests ran the exact same files.

**Comment by santagada** [comment]
Can you either provide a test case (for example the github of your project with steps to set up environment to run tests) or try to profile py.test and manage.py test and post here the results?

**Comment by Pradeek** [comment]
My bad. Turns out `python manage.py test` reports the time *only* for the test run, whereas `py.test` reports the time for the whole running time, including database creation and teardown.

**Comment by pelme** [comment]
Some context on this behaviour: Database setup is handled by pytest fixtures and lazily loaded when the first test actually needs the database. This means that you can run a subset of a test suite that does not need the database, without even connecting to it. It also means that the first test that actually needs the database will "pay" the setup time.
