### ISSUE TITLE
tidy-html5 support

### ISSUE THREAD

**Issue by codingjoe** [pytest-dev/pytest-django#252]
Hey, what do you guys think about adding an additional [tidy-html5](https://github.com/htacg/tidy-html5)  support for the client fixture.
Optional of course and you'd still need to install tidy-html5 yourself. Which isn't that difficult after all.

I think it would be cool to automatically test your html response to be valid. But maybe it's out of scope for the package. What do you think?

**Comment by blueyed** [comment]
I'd like something like that.

I've experimented with using https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py.

I've also stumbled upon https://github.com/peterbe/django-html-validator.

**Comment by blueyed** [comment]
> But maybe it's out of scope for the package.

Yes, probably.

**Comment by codingjoe** [comment]
The Mozilla webQA team has a lot of good stuff, but they're too slow to release. I dislike their solution, as it makes a lot of requests. I don't want to rely on that, considering that the tech behind the API is open source.

I could talk to the travis guys if they would consider shipping their containers with tidy-html5. If not I could write a blog post somewhere on how to compile it on travis and other ci systems.

There is a python wrapper for tidy-html5. I don't know how good they are tho. Proper bindings would be better, but a subprocess does the jobs just as fine.

I'll sketch up a first draft. We can see if it fits in or not.

**Comment by codingjoe** [comment]
@blueyed I took a closer look at [django-html-validator](https://github.com/peterbe/django-html-validator). It look promising. I have a first draft on my local system, it does need some work tho, like proper verbosity. I'll try to put something together that we can use as a base of discussion.

**Comment by pelme** [comment]
I think it is a bit out of scope for pytest-django, but it should be fairly straightforward to do in a separate plugin. The pytest-django `client` fixture is just a really thin wrapper over Django's test client:
https://github.com/pytest-dev/pytest-django/blob/b9eb210e592d15ef0e7f3fc50cb89c9c72fb44a4/pytest_django/fixtures.py#L198-L205

**Comment by codingjoe** [comment]
Understood, I'd still like you to review it. I'll keep you posted on my progress.

**Comment by bluetech** [comment]
Closing as out of scope.
