### ISSUE TITLE
Add `pytest.mark.transactional_db` if `transactional_db` fixture is used

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#263]
While using `@pytest.mark.transactional_db` will use the `transactional_db` fixture automatically, a test using the `transactional_db` fixture won't be marked as `pytest.mark.transactional_db`.

Is this intended?
Could/should it be fixed?

**Comment by pelme** [comment]
It is hard/impossible to get this right in all cases unfortunately. Marks need to be applied at collection time to be useful (with `-m foo`) for instance. However, fixtures can be requested dynamically during test run via `request.getfuncargvalue`.
