### ISSUE TITLE
django-configurations is by now unmaintained

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-django#267]

**Comment by blueyed** [comment]
Yes, it's unfortunate that a new release is not being made since a while, and it seems like offers for help with maintaining are ignored.

See e.g. https://github.com/jezdez/django-configurations/commit/0ff4c7612d28036449edd4b2cf3b58ca1eded0f2, and various tweets, especially from you.

**Comment by blueyed** [comment]
Not much we can do about it from here.

**Comment by pelme** [comment]
I'd like to be able to deprecate django-configurations support in pytest-django, regardless of the upstream status: All sorts of customized django settings in project's `pytest_configure` hook should be possible.

I.e. a project using django-configurations can use something like:

```python
def pytest_configure():
    os.environ['DJANGO_SETTINGS_MODULE'] = 'foo.bar'
    os.environ['DJANGO_CONFIGURATION'] = 'Dev'
    import configurations.importer
    configurations.importer.install()
```

I just tested this and it works with current master as long as `DJANGO_SETTINGS_MODULE` is not defined before launching `py.test`. I propose we add something like `--skip-django-settings` or similar that will just ignore the setup that pytest-django does with regard to settings.

Of course this needs to be clearly documented with copy-pasteable code. 

@blueyed @RonnyPfannschmidt what do you think about that approach?

**Comment by RonnyPfannschmidt** [comment]
@blueyed seems legitimate - the next release should show  a pytest-warning?

**Comment by blueyed** [comment]
@pelme 
Seems fine for me, and might simplify a lot of things.
OTOH we could then still detect `DJANGO_CONFIGURATIONS` like before, and therefore support it further.

**Comment by pelme** [comment]
I think we should issue a pytest warning when used with django-configurations, but keep the support for quite some time (until it becomes an issue to maintain it). It's already there, tested and works so I don't see any reason to drop it.

**Comment by marctc** [comment]
The [jazzband](https://jazzband.co/) cooperative will continue with [django-configurations](https://github.com/jazzband/django-configurations) support. They released a new version which is fully compatible with Django >= 1.8 . So I think that a deprecation warning is no longer needed on pytest-django.

**Comment by blueyed** [comment]
Yup, closing.
