### ISSUE TITLE
using django-classy-settings requires stange hacks

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-django#268]

**Comment by blueyed** [comment]
I assume you'll prepare a PR (given your tweet)?
Otherwise, please be more verbose here - which would be good in general, too.. :)

**Comment by RonnyPfannschmidt** [comment]
more context

with dcs you need an `cbr.apply(YourSettingsClass, your_settings_module.__dict__)` before settings are availiable, since it doesnt share the messy hacks with django-configurations

**Comment by blueyed** [comment]
PR: https://github.com/pytest-dev/pytest-django/pull/271

Can this issue be closed, and we'll discuss it further on the PR?
(maybe take over your comment then)

**Comment by RonnyPfannschmidt** [comment]
yup
