### ISSUE TITLE
Broken link in tutorial

### ISSUE THREAD

**Issue by dAnjou** [pytest-dev/pytest-django#269]
This one in `pytest-django/docs/tutorial.rst`:

> Blog post: [Django Projects to Django Apps: Converting the Unit Tests, by John Costa](http://www.johnmcostaiii.net/2013/django-projects-to-django-apps-converting-the-unit-tests/).

**Comment by pelme** [comment]
Thanks for the report. It seems that this link works now, so I'm closing this issue! 😄

**Comment by murdav** [comment]
I reopen this issue because the link doesn't work anymore.

**Comment by anshulxyz** [comment]
Reopen the issue, as the link has been changed to https://www.johnmcostaiii.net/post/2013-04-21-django-projects-to-django-apps-converting-the-unit-tests/

from https://www.johnmcostaiii.net/2013/django-projects-to-django-apps-converting-the-unit-tests/

**Comment by haydotech** [comment]
Reopen this issue because the proposed [link](https://johnmcostaiii.net/post/2013-04-21-django-projects-to-django-apps-converting-the-unit-tests/) is broken again.
