### ISSUE TITLE
2.9.1: AttributeError with Django TestCase

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#282]
With pytest-django 2.9.1, there are new failures with django-autocomplete-light's tests now:
https://travis-ci.org/yourlabs/django-autocomplete-light/jobs/83973352

    ____________ InlineBlankTestCase.test_autocomplete_has_four_choices ____________

    self = <autocomplete_light.tests.test_widget.InlineBlankTestCase testMethod=test_autocomplete_has_four_choices>

        def setUp(self):

            if self.__class__.test_case_setup_done is False:

    >           self.set_implicit_wait()

    autocomplete_light/tests/test_widget.py:87: 

    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self = <autocomplete_light.tests.test_widget.InlineBlankTestCase testMethod=test_autocomplete_has_four_choices>

        def set_implicit_wait(self):

    >       self.selenium.implicitly_wait(WAIT_TIME)

    E       AttributeError: 'InlineBlankTestCase' object has no attribute 'selenium'

    autocomplete_light/tests/test_widget.py:171: AttributeError

Just wanted to let you know, have not investigated.

Likely related to https://github.com/pytest-dev/pytest-django/commit/1bf4920dd202ebd0a954ef455f19857b2e626d50.

**Comment by pelme** [comment]
Hmm, do you know if setUpClass gets called?

**Comment by blueyed** [comment]
@pelme
Not from the top of my head, but @jpic can probably help out here.

**Comment by jpic** [comment]
setUpClass is run apparently:

```
$ tox -e py27-django15 -- -x -s
py27-django15 develop-inst-nodeps: /home/jpic/env/src/autocomplete-light
py27-django15 installed: cssselect==0.9.1,Django==1.5.12,-e git+git@github.com:yourlabs/django-autocomplete-light.git@4fafc72c546c0f3b25a1bbb41b923fb934404b0d#egg=django_autocomplete_light-2.2.10,django-autoslug==1.8.0,django-cities-light==3.1.2,funcsigs==0.4,lxml==3.4.4,mock==1.3.0,pbr==1.8.0,py==1.4.30,pytest==2.8.2,pytest-django==2.8.0,selenium==2.48.0,six==1.10.0,South==1.0.2,Unidecode==0.4.18,wheel==0.24.0
py27-django15 runtests: PYTHONHASHSEED='4138848345'
py27-django15 runtests: commands[0] | py.test --strict -r fEsxXw -x -s
==================================== test session starts ====================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/jpic/env/src/autocomplete-light, inifile: pytest.ini
plugins: django-2.8.0
collected 408 items 

autocomplete_light/tests/test_dependent.py 
>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/jpic/env/src/autocomplete-light/autocomplete_light/tests/test_widget.py(75)setUpClass()
-> if os.environ.get('TESTS_SKIP_LIVESERVER', False):
(Pdb) l
 70  	    test_case_setup_done = False
 71  	
 72  	    @classmethod
 73  	    def setUpClass(cls):
 74  	        import pdb; pdb.set_trace()
 75  ->	        if os.environ.get('TESTS_SKIP_LIVESERVER', False):
 76  	            raise unittest.SkipTest('TESTS_SKIP_LIVESERVER enabled')
 77  	
 78  	        cls.selenium = Selenium()
 79  	        super(WidgetTestCase, cls).setUpClass()
 80  	
```

**Comment by blueyed** [comment]
Seems to be triggered by old-style classes: https://github.com/yourlabs/django-autocomplete-light/pull/508

**Comment by pelme** [comment]
Hmm, that's weird. Do you know if the old-style class runs properly with Django's test runner?

**Comment by pelme** [comment]
Do you think this can/should be fixed?

**Comment by blueyed** [comment]
We're currently pinning pytest-django in this project, but I have not tried latest master with it.
It would be nice to have fix for this, of course.

**Comment by pelme** [comment]
Do you need to pin it when your Selenium class is new style?

If the same thing works in with `manage.py test`, it should be fixed, otherwise I think we should just leave it.

**Comment by Deepakdubey90** [comment]
Hi, 
I'm trying to use a decorator **"@client_login"** before every assertion in D**jango-unit test-case**.
I was expecting that **"setUpModule** " should execute first then Decorator should be resolve .

but Actually test-case loader is trying to resolve decorator first & the loading the setup module .

Is there anyway to load **setUpModule** forcefully before **"Login" decorator**.

**Comment by jpic** [comment]
I suggest we consider this as a documentation issue and recommend new style classes.

**Comment by pelme** [comment]
I'm going to close this issue now since it is fixed.

@Deepakdubey90 This does not seem related to this issue, please open a new issue if your problem still persists!

@jpic Me and @blueyed had a quick chat about this on the pytest sprint but could not figure out an obvious place to document this. Please submit a PR for this if you figure out a good way to document it. :)
