### ISSUE TITLE
Test case using transaction aren't isolated on the non default databases

### ISSUE THREAD

**Issue by xordoquy** [pytest-dev/pytest-django#286]
This is a regression I have with pytest-django 2.9 - doesn't happen with 2.8. Django is 1.7.1, py.test 2.8.2 and Python 3.4.
Some of my tests are using transactions and aren't run in isolation to each other any longer. They are part of a `unittest.TestCase`.
Performing a git bisect, the commit 0ec741bd68028ac471bd10a53fbb87949f455a4f seems to introduce the regression.

This is probably due to the fact that it now only applies rollbacks to Django TestCase and no more with unittest's ones.

**Comment by blueyed** [comment]
So it is about transactional_db, right?

**Comment by xordoquy** [comment]
indeed, sorry, should have mentioned it.

**Comment by blueyed** [comment]
Thanks for notifying us, and bisecting it.

Can you come up with a test case, based on the existing ones?
I would have thought that this is tested already, but we're not using transactions in there then probably.

**Comment by xordoquy** [comment]
ah, sorry, I'm confusing terms.
I don't use the transactional_db feature. The file is marked as pytest.mark.django_db(transaction=True)

**Comment by xordoquy** [comment]
Will try to get a test case for it though won't be able to work on this before next week.

**Comment by blueyed** [comment]
> I don't use the transactional_db feature. The file is marked as pytest.mark.django_db(transaction=True)

That is quite the same though, just another way to mark/express it.

**Comment by xordoquy** [comment]
OK, I've been trying to reproduce the issue but failed.
I've probably missed a point in my initial analysis. The real project uses a multi database configuration and the secondary databases aren't rolled back. It's not the use of `unittest.TestCase` that causes this isolation issue.

Will try to get a failing test case but it'll be slightly more complex.

**Comment by blueyed** [comment]
@xordoquy 
Thanks for reporting back.
It would be sweet nonetheless to have some extra test to make sure it works as expected, in case it's not tested for already.  Please let us know about your findings and keep that (contributing extra tests) in mind.

**Comment by xordoquy** [comment]
@blueyed that's on my todo list. Could find some time to work on this today, I was just reporting back.

**Comment by bluetech** [comment]
Closing this issue as it's probably no longer relevant.
