### ISSUE TITLE
Please included tests in pypi release

### ISSUE THREAD

**Issue by jlec** [pytest-dev/pytest-django#290]
Downstream developers love to test during installation and packaging. Please include tests.

**Comment by pelme** [comment]
I would be happy to include tests in the distribution, but have not the motivation to work on this right now. Please send a PR and I will make sure to merge it.

**Comment by blueyed** [comment]
@jlec 
This was never fixed - https://github.com/pytest-dev/pytest-django/pull/296/files included "test", but tests are in tests.
Also "pytest_django_test" would need to be included then I assume.
