### ISSUE TITLE
Cannot specify reset_sequences on a transactional test

### ISSUE THREAD

**Issue by cb109** [pytest-dev/pytest-django#299]
This is more of a question than an actual issue, please bear with me if it is the wrong place to ask: I have a few tests that rely on ids, which is an issue with PostgreSQL since it does not reset its id counter across tests by default. The TransactionTestCase has a flag to force an id reset: https://docs.djangoproject.com/en/dev/topics/testing/advanced/#django.test.TransactionTestCase.reset_sequences

Do you support setting this flag by a mark or similar (I could not find it yet if existing)? I have currently fallen back to rewriting the test to use the Django testcase but would like to not mix unittest and pytest styles if possible. 

If there is no official support yet, would you be be interested in that? I would gladly propose a patch.

**Comment by pelme** [comment]
It is currently not possible without falling back to Django's `TransactionTestCase`. A PR that allows reset_sequences something like

`@pytest.mark.django_db(transaction=True, reset_sequences=True)`

would make sense and is welcome. Thanks!

**Comment by cb109** [comment]
Implemented in #308
