### ISSUE TITLE
liveserver settings ignore at some cases

### ISSUE THREAD

**Issue by zdenekmaxa** [pytest-dev/pytest-django#300]
[ http://stackoverflow.com/questions/34276468/django-pytest-liveserver-settings-issue ]

when using django-pytest along with the live server, according to the documentation, the live server setting can be done in these ways:

- in the settings *.py such as: DJANGO_LIVE_TEST_SERVER_ADDRESS="localhost:12588"

- in the pytest pytest.ini file: DJANGO_LIVE_TEST_SERVER_ADDRESS="localhost:12588" (tried as well DJANGO_LIVE_TEST_SERVER_ADDRESS=localhost:12588)

in these both cases, the value was not taken into account and still the first source code defined default localhost:8081 was used.

what worked was following (from CLI):

py.test --liveserver localhost:12588

I am using Django 1.7 and platform linux2 -- Python 2.7.6, pytest-2.8.4, py-1.4.31 [pytest] plugins: django-2.9.1

The DJANGO_LIVE_TEST_SERVER_ADDRESS seems to be ignored in the aforementioned cases.

**Comment by ttanner** [comment]
It seems this is a more general problem: pytest.ini settings are ignored for pytest-django.
For example, DJANGO_CONFIGURATION in pytest.ini is ignored, but taken into account if I set it as environment variable.
I found that plugin.py:pytest_load_initial_conftests of pytest-django is not even called
and, by the way, seems to have a wrong parameter order. The correct one is 
pytest_load_initial_conftests(args, early_config, parser)
Fixing the order has no effect.

**Comment by blueyed** [comment]
> DJANGO_CONFIGURATION in pytest.ini is ignored

Just a guess: do you have a `setup.cfg` that is used instead (and results in skipping `pytest.ini`)?!

> by the way, seems to have a wrong parameter order. The correct one is pytest_load_initial_conftests(args, early_config, parser)

Seems like the documentation is wrong for that one; I've submitted a PR for pytest at: https://github.com/pytest-dev/pytest/pull/1451.

**Comment by RonnyPfannschmidt** [comment]
the order is irrelevant - calls are done by name not by argument position

**Comment by pelme** [comment]
Please get back if you actually have a `setup.cfg` or `tox.ini` with a pytest section as @blueyed asked above. If that is not the problem, can you try to make this reproducable so we can find the source of the issue?

As pointed out by @RonnyPfannschmidt, the order in pytest hooks should not affect this. 

I'm closing this for now, please get back with more information and reopen the issue if this problem still exists.

**Comment by Pijukatel** [comment]
Hello, 

I have encountered the same issue. I attach debugging screenshot to show, that it correctly reads the address from pytest.ini, but it does not use it. I do not have any setup.cfg or tox.ini.  I could not find any part of code, that would set this address as environment variable and as you can see in screenshot, the environment variable of that name is not set. Maybe I misunderstood how this is supposed to be used?
(Using command py.test --liveserver ... works fine)

![DJANGO_LIVE_TEST_SERVER_ADDRESS](https://user-images.githubusercontent.com/78099797/118396095-1de23380-b64e-11eb-8bc5-36e0f9b699da.png)
