### ISSUE TITLE
Relative import problem

### ISSUE THREAD

**Issue by socketubs** [pytest-dev/pytest-django#303]
Hi there,

Today, I was refactoring a django project with this structure:
```
my_app/models.py
my_app/apps.py
my_app/api/views.py
my_app/api/serializers.py
```
My `my_app/api/views.py` have this content:

```
from ..models import MyModel
```

Everything is running smooth with `manage.py test` but `py.test` (with of course `pytest-django` plugin) raise this:

```
================================ ERRORS ====================================
___________________ERROR collecting my_app/api/views.py ____________________
my_app/api/views.py:1: in <module>
    from ..models import MyModel
E   SystemError: Parent module '' not loaded, cannot perform relative import
========================== short test summary info =========================
ERROR my_app/api/views.py
!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!
========================= 1 error in 0.48 seconds ==========================
```

Any advice ?
Thanks ! :smile:

**Comment by bh** [comment]
Missing `__init__.py`?

**Comment by socketubs** [comment]
Yes... :shipit: 
But its strange that Django have no problem loading tests with  `./manage.py tests` and py.test failed.

Sorry about inconveniences.

**Comment by pelme** [comment]
It looks like pytest is trying to collect your application files as test files. This is probably not what you want, try putting

```
[pytest]
norecursedirs = my_app
```

in `pytest.ini`.

I don't think this is a bug in pytest-django, but if the problem still persists, feel free to reopen this issue with more information. 😃
