### ISSUE TITLE
Migrations fail silently

### ISSUE THREAD

**Issue by lee-kagiso** [pytest-dev/pytest-django#306]
If I run `py.test --create-db` with migrations that don't work in dev, py.test just swallows them up and a lot of tests fail due to missing columns etc.

**Comment by blueyed** [comment]
Can you provide a migration that triggers it?
Is it caused by any exception?

**Comment by lee-kagiso** [comment]
I don't actually have the migration anymore sadly.

Something that would make the migration irrelevant would be to print out
the same output as you would get from `manage.py migrate`
when using the --create-db option. Currently it is silent.

**Comment by pelme** [comment]
I did a quick test and can confirm that this is an issue. Just introducing any error (raising an exception/spelling a field wrong etc) in a migration file does not give any error output and still runs tests.

**Comment by bluetech** [comment]
From experience this does not happen anymore. Since a lot of time has passed, I'll close this. If anyone can provide a reproduction, will be happy to reopen.
