### ISSUE TITLE
Error running py.test --help if DJANGO_SETTINGS_MODULE is set in pytest.ini

### ISSUE THREAD

**Issue by carljm** [pytest-dev/pytest-django#307]
It seems that when I run `--help` all the Django settings setup is skipped, but `pytest_configure` still runs and runs `_setup_django()`, which requires that settings are configured.

Either the DJANGO_SETTINGS_MODULE stuff in `pytest_load_initial_conftests` still needs to run in all cases, or else `pytest_configure` needs to avoid calling `_setup_django()` if we're just asking for help or version.

**Comment by carljm** [comment]
Confirmed that this is fixed if I wrap the call to `_setup_django()` in `pytest_configure` with an `if not (config.options.help or config.options.version):` (means that `pytest_configure` needs to request the `config` fixture).

**Comment by carljm** [comment]
Fixed by 211495b66c600afe232e716397457efff4f51239

**Comment by blueyed** [comment]
@carljm 
Thanks for reporting back!
