### ISSUE TITLE
[question] how to do response assertContain in pytest?

### ISSUE THREAD

**Issue by mtermoul** [pytest-dev/pytest-django#315]
I am trying this

```
def test_main_view_get_content(self, client):
        url = reverse("main")
        res = client.get(url)
        assert 'Hello' in str(res.content)
```

but it's not working.

**Comment by blueyed** [comment]
What does not work?
(The 'self' should not be there probably.)

**Comment by das-g** [comment]
Note that
```python
self.assertContains(res, 'Hello')
```
in a test method within a `django.test.testcases.SimpleTestCase`-based TestCase does more than just what
```python
assert 'Hello' in str(res.content)
```
would do: `assertContains` also [checks the status code](https://github.com/django/django/blob/d2569f89f28883d07ede0e44a0a69ae678d3b35f/django/test/testcases.py#L337) for whether `res` ["indicates that some content was retrieved successfully"](https://github.com/django/django/blob/d2569f89f28883d07ede0e44a0a69ae678d3b35f/django/test/testcases.py#L362).

**Comment by blueyed** [comment]
We could have this with https://github.com/pytest-dev/pytest-django/pull/232 - which appears to have stalled currently (again).

**Comment by pelme** [comment]
Yes, unfortunately this is not supported by pytest-django. You can still use Django TestCase subclasses in the places where you depend on these helpers.

As pointed out by @blueyed, #232 is the issue which tracks the helpers to provide this functionality in pytest-django.
