### ISSUE TITLE
remove support of unsupported django versions in next release. [ideally lower then 1.8]

### ISSUE THREAD

**Issue by auvipy** [pytest-dev/pytest-django#320]
will be happy to work on the issue and send PR

**Comment by auvipy** [comment]
@blueyed input?

**Comment by blueyed** [comment]
In my opinion we should not drop support without any reasons.
In case a new feature cannot be easily supported by older versions I'd rather not support that feature there..

@pelme 
What do you think?

**Comment by auvipy** [comment]
django 1.4, 1.5, 1.6 and 1.7 reached their EOL stage long before, python 2.6, 3.2, 3.3 is no more supported in django 1.8 any more. my thoughts are we should remove obsolete python and django versions from tests first and graduality removing obsolete versions specific feature and shims. this will reduce the maintenance overhead and technical difficulties, as django newer versions are changing heavily under the hood. thoughts?

**Comment by auvipy** [comment]
any one interested to use pytest in older versions should use older versions of pytest django.

**Comment by blueyed** [comment]
This has been fixed by @pelme in https://github.com/pytest-dev/pytest-django/commit/8e6fab6f93e8fe8c2474c8971f8774322d13d7ee / #348.
