### ISSUE TITLE
django_db mark doesn't always fail if database accessed through one of its @cached_property

### ISSUE THREAD

**Issue by lsglick** [pytest-dev/pytest-django#325]
We had some tests fail when run independently due to not using `django_db` marker. However when run in a suite, they'd always pass.

It turns out we are accessing some `@cached_property`s on the mysql `DatabaseWrapper`. So, they would only fail if run before another test had successfully cached the value.

E.g. https://github.com/django/django/blob/master/django/db/backends/mysql/base.py#L184, https://github.com/django/django/blob/master/django/db/backends/mysql/features.py#L51.

Obviously these tests should be failing without the marker as they depend on the db, but they should be failing always.

Are there any easy workarounds here? Only thing I can think of would be to monkey patch `cached_property`?

**Comment by adamchainz** [comment]
If you install [pytest-randomly](https://github.com/adamchainz/pytest-randomly) your tests will be randomly ordered so if you introduce such a dependency it would eventually fail on a test run.

**Comment by blueyed** [comment]
I think this might be fixed by https://github.com/pytest-dev/pytest-django/pull/350.

**Comment by blueyed** [comment]
#350 is merged now - I am closing this issue for now.

Please re-open it in case it's still a problem with master / the next release (3.0 probably).
