### ISSUE TITLE
string_if_invalid error with Django Jinja2 templates backend

### ISSUE THREAD

**Issue by MikeVL** [pytest-dev/pytest-django#327]
```
tests/news/test_controlpanel.py:197: in test_news_drafts_update_moderated
    response = self.client.get(url)
/usr/local/lib/python2.7/dist-packages/django/test/client.py:500: in get
    **extra)
/usr/local/lib/python2.7/dist-packages/django/test/client.py:303: in get
    return self.generic('GET', path, secure=secure, **r)
/usr/local/lib/python2.7/dist-packages/django/test/client.py:379: in generic
    return self.request(**r)
/usr/local/lib/python2.7/dist-packages/django/test/client.py:448: in request
    response = self.handler(environ)
/usr/local/lib/python2.7/dist-packages/django/test/client.py:122: in __call__
    response = self.get_response(request)
/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py:218: in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py:268: in handle_uncaught_exception
    return callback(request, **param_dict)
/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py:71: in view
    return self.dispatch(request, *args, **kwargs)
/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py:89: in dispatch
    return handler(request, *args, **kwargs)
/usr/local/lib/python2.7/dist-packages/django_jinja/views/__init__.py:25: in get
    output = loader.render_to_string(self.tmpl_name, context, request=request)
/usr/local/lib/python2.7/dist-packages/django/template/loader.py:98: in render_to_string
    template = get_template(template_name, using=using)
/usr/local/lib/python2.7/dist-packages/django/template/loader.py:29: in get_template
    engines = _engine_list(using)
/usr/local/lib/python2.7/dist-packages/django/template/loader.py:143: in _engine_list
    return engines.all() if using is None else [engines[using]]
/usr/local/lib/python2.7/dist-packages/django/template/utils.py:110: in all
    return [self[alias] for alias in self]
/usr/local/lib/python2.7/dist-packages/django/template/utils.py:101: in __getitem__
    engine = engine_cls(params)
/usr/local/lib/python2.7/dist-packages/django_jinja/backend.py:182: in __init__
    self.env = environment_cls(**options)
E   TypeError: __init__() got an unexpected keyword argument 'string_if_invalid'
```

**Comment by sasha0** [comment]
@MikeVL I suppose this error has nothing to do with pytest-django, it's just misconfigured template engine.

I'd suggest to remove `string_if_invalid` from `OPTIONS` dictionary of template engine settings and check if all necessary options are in place according to documentation https://docs.djangoproject.com/en/1.9/topics/templates/#django.template.backends.jinja2.Jinja2.

**Comment by pelme** [comment]
@MikeVL Please get back with more information and follow up @sasha0 s comment  if this is an issue in pytest-django. It is not clear exactly what you are proposing here.

**Comment by PiotrOrzechowski** [comment]
I have the same exception with `Python 3.6.1`, `Django 1.11.3`, `pytest-django 3.1.2` and `Jinja2 2.9.6` when `--fail-on-template-vars` flag is set in `pytest.ini`.

I have set Django up to use Jinja2 templating engine according to [this section](https://docs.djangoproject.com/en/1.11/topics/templates/#django.template.backends.jinja2.Jinja2).

When `--fail-on-template-vars` flag is set, then `project_name.jinja2.environment` function is being called with the following options:
```
{
    'string_if_invalid': <pytest_django.plugin._fail_for_invalid_template_variable.<locals>.InvalidVarException object at (some_addr)>,
    'loader': <jinja2.loaders.FileSystemLoader object at (some_addr)>,
    'autoescape': True,
    'auto_reload': False,
    'undefined': <class 'jinja2.runtime.Undefined'>
}
```

Apparently the [jinja2.environment.Environment.\_\_init\_\_](https://github.com/pallets/jinja/blob/2.9.6/jinja2/environment.py#L264) method doesn't have the `string_if_invalid` parameter at all, thus
```
    def environment(**options):
        print('FAILED OPTIONS: ' + str(options))
>       env = Environment(**options)
E       TypeError: __init__() got an unexpected keyword argument 'string_if_invalid'
```
exception is raised.

When the `--fail-on-template-vars` flag is not set, then the following options are passed to environment function:
```
{
    'loader': <jinja2.loaders.FileSystemLoader object at (some_addr)>,
    'autoescape': True,
    'auto_reload': False,
    'undefined': <class 'jinja2.runtime.Undefined'>
}
```
and no exception is raised.

I guess the workaround would be to filter out the offending parameter before passing options to `jinja2.environment`, but then the `--fail-on-template-vars` flag would make no effect in Jinja2 templates, right?

**Comment by PiotrOrzechowski** [comment]
To anyone having the same issue:

I get the same exception with `Python 3.6.1`, `Django 1.11.3`, `pytest-django 3.1.2` and `Jinja2 2.9.6` when `--fail-on-template-vars` flag is set in `pytest.ini`.

I have set Django up to use Jinja2 template engine according to [this section](https://docs.djangoproject.com/en/1.11/topics/templates/#django.template.backends.jinja2.Jinja2).

When `--fail-on-template-vars` flag is set, then `project_name.jinja2.environment` function is being called with the following options:
```
{
    'string_if_invalid': <pytest_django.plugin._fail_for_invalid_template_variable.<locals>.InvalidVarException object at (some_addr)>,
    'loader': <jinja2.loaders.FileSystemLoader object at (some_addr)>,
    'autoescape': True,
    'auto_reload': False,
    'undefined': <class 'jinja2.runtime.Undefined'>
}
```

Apparently the [jinja2.environment.Environment.\_\_init\_\_](https://github.com/pallets/jinja/blob/2.9.6/jinja2/environment.py#L264) method doesn't have the `string_if_invalid` parameter at all, thus
```
    def environment(**options):
>       env = Environment(**options)
E       TypeError: __init__() got an unexpected keyword argument 'string_if_invalid'
```
exception is raised.

When the `--fail-on-template-vars` flag is _not_ set, then the following options are passed to environment function:
```
{
    'loader': <jinja2.loaders.FileSystemLoader object at (some_addr)>,
    'autoescape': True,
    'auto_reload': False,
    'undefined': <class 'jinja2.runtime.Undefined'>
}
```
and exception is _not_ raised.

The workaround is be remove the offending parameter before passing options to `jinja2.environment`:

```
def environment(**options):
    options.pop('string_if_invalid', None)
    env = Environment(**options)
    env.globals.update({
        'static': staticfiles_storage,
        'url': reverse,
    })
    return env
```
