### ISSUE TITLE
New release / fix for `--help`

### ISSUE THREAD

**Issue by kottenator** [pytest-dev/pytest-django#328]
`pytest-django==2.9.0,2.9.1` has this bug - #307. You've fixed it 2 months ago but still haven't released the fix.

Could you, please, release version `2.9.2`?

**Comment by blueyed** [comment]
See also #317..

Assigning to @pelme.

**Comment by pelme** [comment]
I'm closing this issue for now, we will make sure to put out a new release shortly after the pytest sprints.

**Comment by jleclanche** [comment]
I was just about to open an issue about this, found out it's already fixed. I agree a release would be very welcome, this is a pretty critical issue imho.
