### ISSUE TITLE
extra_fields in admin_user fixture

### ISSUE THREAD

**Issue by stleon** [pytest-dev/pytest-django#330]
In **admin_user** fixture will be nice to set not empty **extra_fields**:
```
@pytest.fixture()
def admin_user(db, django_user_model, django_username_field):
    """A Django admin user.
    This uses an existing user with username "admin", or creates a new one with
    password "password".
    """
    UserModel = django_user_model
    username_field = django_username_field

    try:
        user = UserModel._default_manager.get(**{username_field: 'admin'})
    except UserModel.DoesNotExist:
        extra_fields = {}
        if username_field != 'username':
            extra_fields[username_field] = 'admin'
        user = UserModel._default_manager.create_superuser(
            'admin', 'admin@example.com', 'password', **extra_fields)
    return user
```

By default extra fields are empty and I can't set required fields for my user model.

Thanks!

**Comment by blueyed** [comment]
Can you post a diff/PR for this, please?

**Comment by pelme** [comment]
Me and @blueyed had some discussions about this on the pytest sprint.

We think that the recommended to solve issues like this would be to create your own fixture:

```python
@pytest.fixture
def my_admin_user(db):
    return MyUser.objects.create_superuser(first_name='foo', last_name='bar')
```

It should make your code clearer: you wouldn't have to look up how `django_user_model`, `django_username_field` and `django_user_model_extra_fields` interact together.

Thanks for creating a PR and sorry for having not figured out this earlier, however, we believe that this would be the best for your project and for everyone else.
