### ISSUE TITLE
Skip database creation?

### ISSUE THREAD

**Issue by mgallagher** [pytest-dev/pytest-django#332]
Does anyone know if this is possible? I was hoping this would be an option considering the conservative approach pytest-django takes toward database use. We have many tests that don't touch a database, and it would be nice to be able to quickly run these tests without having to run a migration. The `--nomigrations` and `--reuse-db` options are OK workarounds, but still not ideal.

To do this with Django's normal test runner, we just subclassed `DiscoverRunner` and overrode the `setup_databases` and `teardown_databases` functions. With this method, our unit tests run very quickly.

Also, side question: We put unit and integration tests in separate files that use `test_*_unit.py` and `test_*_integration.py` as the names. I can't quite figure out how to target these types of files individually with pytest. With the normal test runner, we'd do `django-admin test --pattern=test_*_unit.py`.

**Comment by blueyed** [comment]
> how to target these types of files 

Just use shell globbing?!  `py.test ... **/test_*_unit.py`

**Comment by pelme** [comment]
The solution is actually very very simple. :)

The database is lazily constructed. It is first created at the point when the first test that needs it is about to be run.

That means that if you just run `py.test test_some_file_without_db_access`, it will run fast and without even connecting to the database.

Feel free to reopen this issue if you have further problems or if there is a bug with this behavior!
