### ISSUE TITLE
use existing database for test

### ISSUE THREAD

**Issue by zibann** [pytest-dev/pytest-django#340]
I can setup a test database beforehand and use it for test in standard django test.  

pytest-django doesn't seem to allow this (it doesn't pick up TEST_RUNNER in settings.py)

**Comment by pelme** [comment]
You can create your database with an external tool before invoking pytest. Then you point your settings to an existing database and then run the tests with `--reuse-db`. That will just use the existing database.

However, I am not sure I understand what you are asking for -- specifying a custom `TEST_RUNNER` is not possible together with pytest. If you are switching to pytest, then pytest will be your test runner. The `TEST_RUNNER` settings is used for Djangos `manage.py test` command.

If you have an existing custom `TEST_RUNNER`, you will need to rewrite using pytest fixtures and/or hooks to achieve the same effect.

Please reopen this issue if there is a bug in pytest-django or if there is something that you think cannot be achieve with a fixture or a hook.

**Comment by pcompassion** [comment]
I needed 

        if DJANGO_VERSION > (1, 7):
            name = db_settings['TEST']['NAME']
        elif DJANGO_VERSION < (1, 7):
            name = db_settings['TEST_NAME']

this part, to reuse the DB.
