### ISSUE TITLE
Override _django_db_setup

### ISSUE THREAD

**Issue by magicjohnson** [pytest-dev/pytest-django#343]
Hi,

I want to override this fixture (basically I need to monkey patch `create_test_db` in special way) and the only option I've found is like https://gist.github.com/magopian/7673776

but it doesn't work for me.

any ideas how to do it?

**Comment by pelme** [comment]
There are a refactor of the internal fixtures in PR #362. Please have a look at it (and especially the documentation on how to use it).

It would be very helpful if you could try out that code in your project and see if it works for you.

It would also be interesting to have some more details on what you are trying to achieve.

**Comment by magicjohnson** [comment]
I need to restore database from sql dump, looks like your solution would work for me.
BTW is it possible to call "super" fixture within overwritten one?

Now I'm using the old version, so I'll try this solution after update.
Thanks.

**Comment by pelme** [comment]
I will add a documentation example on how to create the test database from a sql dump.

You can request a super fixture (with this bit of surprising syntax). It is mentioned in the new docs but I will clarify it:
```python
@pytest.fixture(scope='session')
def django_db_setup(django_db_setup):
    ...  # code that will run once the original django_db_setup has been run
```

If you want to play around with the current master, you can install it in your local environment with
```
pip install -e git+https://github.com/pytest-dev/pytest-django.git#egg=pytest-django
```

**Comment by blueyed** [comment]
Closing, since 3.0 has been released.. :tada:
