### ISSUE TITLE
DB used implicitly with Class Based Views 

### ISSUE THREAD

**Issue by gilmrjc** [pytest-dev/pytest-django#361]
I have the following CBV for my home page:

```python
class HomeView(ListView):
    """Home view."""
    template_name = 'index.html'
    model = Post
    context_object_name = 'posts'
    posts_per_page, _ = Option.objects.get_or_create(name='posts_per_page',
                                                     defaults={'value': '5'}
                                                     )
    try:                                             
        paginate_by = int(posts_per_page.value)
    except ValueError:
        paginate_by = 5
```

When I try to test it I should expect that my test raises an exception telling me to don't use the database, but it just works. In functions defined inside the class like get_context_data I do see that error. I think this is a bug because Django it's not supossed to use the database, not only my code but all Django.

**Comment by blueyed** [comment]
Please try with master, it should be fixed there probably.

**Comment by pelme** [comment]
Django 1.9 should also probably give you an error when running this code with runserver.

**Comment by gilmrjc** [comment]
Thanks for the replies. I notice that Django seems to load CBVs before running and I had to change to a function based view to avoid errors.

Even if pytest-django catches this DB access the app won't work (I can't migrate the DB because the DB is missing). I'll close this issue because this looks more like a Django bug than a bug in this extension.

**Comment by pelme** [comment]
This does not look like a bug in Django or pytest-django, this is just how classes in Python works. It may not obvious at first, but everything that's in a class definition is executed at run time when that module is imported (your if statement and any other valid python code is valid in class definitions!).

That means that you need to be careful with what you put at the module/class level. When working with Django it means that you're not really allowed to issue database queries.

In this case the solution is to override `get_paginate_by`, which will then be called on each request. That's a place where you can properly access the database.

https://docs.djangoproject.com/en/1.9/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.get_paginate_by

I hope this helps!
