### ISSUE TITLE
Request for pytest-django module name warning in docs

### ISSUE THREAD

**Issue by irothschild** [pytest-dev/pytest-django#371]
I think the docs need a big warning to install `pytest-django` and not `django-pytest`. That would have saved me a bit of time! Thanks!

**Comment by blueyed** [comment]
Well, it clearly says `pip install pytest-django` in the README and the Quickstart.
I don't see a point in adding a warning there.

**Comment by blueyed** [comment]
Closing it for now.
But feel free to argue against it.
