### ISSUE TITLE
Provide a context manager/fixture to disable DB access explicitly

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#372]
I think the following code looks weird ,because it reads like it would disable the DB.

    @pytest.fixture
    def myfixture(django_db_blocker):
        with django_db_blocker:
            ...  # modify something in the database

But that's a manager/fixture I would like to have.

What I came up with is this, meant to work with pytest-django master and 2.9.1:

```python
@pytest.yield_fixture
def disable_db(request):
    from _pytest.python import FixtureLookupError
    try:
        manager = request.getfuncargvalue('django_db_blocker')
        manager.disable_database_access()
        yield
        manager.restore_previous_access()
    except FixtureLookupError:
        manager = request.getfuncargvalue('_django_cursor_wrapper')
        manager.disable()
        yield
        manager.restore()
```

**Comment by pelme** [comment]
Hmm, maybe

```
with django_db_blocker:
```

should not be supported, instead we should have:

```
with django_db_blocker.enable_database_access():
```

and

```
with django_db_blocker.disable_database_access():
```

?
enable_database_access / disable_database_access would work both as plain functions and context manager.

That would be nice to change before 3.0 is released to avoid having to support the weird API.

@blueyed thoughts?

**Comment by blueyed** [comment]
@pelme 
Makes sense!

**Comment by blueyed** [comment]
Maybe shorter methods/aliases à la `block` and `unblock`, too?

**Comment by pelme** [comment]
Sure, block / unblock sounds much better. I have a mostly working patch now, will submit soon.

```python

with django_db_blocker.block():
    pass

with django_db_blocker.unblocker():
    pass
```

or manually

```python

django_db_blocker.block()
...
django_db_blocker.restore()


django_db_blocker.unblock()
...
django_db_blocker.restore()
```

looks good?
