### ISSUE TITLE
--pdb breaks django TestCase db flush/rollback

### ISSUE THREAD

**Issue by asfaltboy** [pytest-dev/pytest-django#405]
Added a failing test case in this branch:
https://github.com/asfaltboy/pytest-django/blob/feature/pdb-failure/tests/test_unittest.py#L249

**Comment by blueyed** [comment]
Please submit it as a PR, so we can discuss it here.

**Comment by asfaltboy** [comment]
Latest changes in pytest 3.0.2, cause this, discussion in PR #406
