### ISSUE TITLE
Tests are failing for Django master

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest-django#417]
I'd like to make a release but we should fix this first.

Output from the failing test:
https://travis-ci.org/pytest-dev/pytest-django/jobs/173636497

**Comment by blueyed** [comment]
It seems to be related to the `--nomigrations` hack IIRC.

**Comment by blueyed** [comment]
No sure if I am missing something, but with `--nomigrations` there happens still a bit too much, which can be seen with `pytest -s`:

```
Using existing test database for alias 'default' ('test_app')...
Operations to perform:
  Synchronize unmigrated apps: admin, auth, …, staticfiles
  Apply all migrations: (none)
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
```

Might be nice to avoid/skip this also, when fixing this for Django master.

**Comment by peterlauri** [comment]
Just curious, why do we care for Django-master to pass? Is it just to be able to quickly be able to release a pytest-django when new version of Django comes out? If so, aren't the Django release candidates better approach to not need to maintain and keep releases back just because Django master tests are failing?

**Comment by pelme** [comment]
Some libraries (i.e. djangorestframework) uses pytest-django and tests regularly against Django master. If we do not support Django master properly, those projects can't either.

Also people contributing to Django itself may use pytest-django to test other projects. It can be useful to try out new Django features in real projects test suites before merging to Django.

Therefore we need to be a bit more generous in our supported versions than typical libraries. We also still support Django 1.7 even though it is not supported by Django itself. Getting the test suite to even run is usually the first step to upgrade to new Django versions.

**Comment by peterlauri** [comment]
Sounds fair :)

**Comment by pelme** [comment]
Anyone looking for a new release and found this issue, help fixing the migration problem would be very appreciated 👐 😃

**Comment by peterlauri** [comment]
I'm on it... as I want a release :)

**Comment by pelme** [comment]
@peterlauri you rock! 😅

**Comment by peterlauri** [comment]
#426 fixes this issue... Ready for review and merge => release ;)

**Comment by pelme** [comment]
Thanks! I will run my own test suite with the current master and put out a new release soonish :)

**Comment by peterlauri** [comment]
Gr8!
