### ISSUE TITLE
`--reuse-db` not working with MySQL

### ISSUE THREAD

**Issue by ostrokach** [pytest-dev/pytest-django#418]
Sorry if this is purely a misconfiguration on my end, but I can't get this to work.

I have a MySQL test database that I would like to use for my tests (tests are read-only so the database does not have to be dropped or recreated).

However, running `py.test myapp/tests/ -sv --keep-db` still truncates the tables in the database after every test? 

I tried removing `DROP` privileges from the test user in order to debug this. After the first test, I get the following error:

```
self = <_mysql.connection open to 'XXX.XXX.XXX.XXX' at 2264a88>, query = b'TRUNCATE `auth_permission`;'

    def query(self, query):
        if self.waiter is not None:
            self.send_query(query)
            self.waiter(self.fileno())
            self.read_query_result()
        else:
>           _mysql.connection.query(self, query)
E           django.core.management.base.CommandError: Database test_db couldn't be flushed. Possible reasons:
E             * The database isn't running or isn't configured correctly.
E             * At least one of the expected database tables doesn't exist.
E             * The SQL was invalid.
E           Hint: Look at the output of 'django-admin sqlflush'. That's the SQL this command wasn't able to run.
E           The full error: (1142, "DROP command denied to user 'username'@'hostname' for table 'auth_permission'")
```

**Comment by pelme** [comment]
The database reuse only applies to database schema creation. Reuse means it will reuse an existing database without running all migrations.

If you have transactional tests (Django TransactionalTestCase subclasses or `transactional_db` tests, all tables will be truncated after each test to ensure that each test gets a clean database. This is usually what you want when writing tests to ensure that no database state is left behind.

(I created a small example project and tested it out and it seems to work. I've added an example to the docs to cover this use case:

http://pytest-django.readthedocs.io/en/latest/database.html#use-a-read-only-database

Try it out and open a new issue if the documentation needs further clarification or if there is anything else we can do to support your use case better!
