### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by peterlauri** [pytest-dev/pytest-django#419]
Is there any planned release? I cannot see any milestone nor information about any planned 3.X.X release?

**Comment by blueyed** [comment]
Implicitly: https://github.com/pytest-dev/pytest-django/issues?q=is%3Aissue+is%3Aopen+label%3Arelease-blocker ;)

**Comment by blueyed** [comment]
Specifically: https://github.com/pytest-dev/pytest-django/issues/417

**Comment by peterlauri** [comment]
So only #417 will be included? No others?

**Comment by blueyed** [comment]
#417 is the blocker for everything that is merged already.
You could use master through Git already.

**Comment by peterlauri** [comment]
I have had #323 PR ready for merging since 9th September, just hanging in there without any comments.

Also, of course #410 that I have been working on last few days.

**Comment by blueyed** [comment]
Oh, sorry - misunderstood.
I've reviewed #323.  #410 is too much for my tired eyes now.

**Comment by blueyed** [comment]
I've also created https://github.com/pytest-dev/pytest-django/milestone/4.

**Comment by peterlauri** [comment]
My tired eyes shouldn't be at github right now :) My eyes should be closed, as my flight to Paris for France-Sweden in football leaves in 4 hours and 20 minutes ;)

Thanks for feedback on #323!

#410 should keep your eyes open ;)

**Comment by peterlauri** [comment]
Thanks for creating the milestone, if it will contain the issues really included in 3.1... It would be nicer for contributors to be able to see where help is needed, and where to put the efforts... And to see what nice features are coming to the next releases of pytest-django...
