### ISSUE TITLE
feature request: user_client fixture

### ISSUE THREAD

**Issue by nirizr** [pytest-dev/pytest-django#424]
In multiple cases I would like to test different behavior between an admin and an authenticated user. For example, admins are allowed to delete/modify everyone's data while a user is only allowed to delete/edit his own data.
I think many pytest-django users could use a `user_client` fixture for a regular logged in user.

Is this something that already came up? Will you be willing to consider this?

Thanks

**Comment by blueyed** [comment]
@nirizr 
Thanks for the suggestion, but the recommended way is to create such a fixture yourself: there is no "canonical" user that would fit all use cases.

**Comment by nirizr** [comment]
I thought a set of (anon, user, admin) has a good trade-off, but i guess that's a matter of taste. Thanks for the prompt reply!
