### ISSUE TITLE
[proposition] WebTest integration

### ISSUE THREAD

**Issue by dszmaj** [pytest-dev/pytest-django#425]
Have you thought to integrate this repo into a fixture for pytest?
https://github.com/django-webtest/django-webtest

it would be extremely great to be able to use webtest like this
```python
@pytest.mark.django_db
def test_django(app):
    resp = app.get('/smth/', user='smone')
    form = resp.forms['main']
    form['some_field'] = 'smth'
    submitted = form.submit()
    assert submitted.status_int == 200
```

**Comment by pelme** [comment]
I think the proper place for such a fixture would be django-webtest. It could be a pytest plugin itself (that just defines a setuptools entrypoint) that just provides an app fixture. It could also be slightly refactored to make it easier to call into the settings modification code that would make creating a project-fixture trivial.
