### ISSUE TITLE
Loading of Django signals

### ISSUE THREAD

**Issue by jamescooke** [pytest-dev/pytest-django#438]
In a test suite I'm working with, there are a couple of models that have immutable UUID fields - this protection is provided by a `pre_save` signal in the Django app. It looks like this:

```py
@receiver(pre_save, sender=PullRequest)
def check_change_uuid(sender, instance, **kwargs):
    """
    Before model that entends UUIDModel is saved, ensure that its UUID has not
    changed.

    Raises:
        ValidationError: If uuid of the model has been found to change.
    """
    ...
```

To ensure that this is wired in correctly I have a test that attempts to change the UUID field in the `PullRequest` instance which expects a `ValidationError` to be raised:

```py
@pytest.mark.django_db
def test_uuid_permanent():
    """
    PullRequest instances have immutable UUIDs

    Trusts:
        test_signals: A helpful message is raised.
    """
    repo = PullRequest.objects.create(
        repository=RepositoryFactory(),
    )
    repo.uuid = uuid.uuid4()

    with pytest.raises(ValidationError):
        repo.save()
```

This test fails when run in isolation - but passes when the whole suite is run.

In order to fix the test to work in isolation, I've explicitly imported the signals at the top of the test file:

```py
from ...signals import check_change_uuid
```

... and the test passes again.

**What is the correct way with `pytest-django` to turn on Django signals for a test?**

I've searched the docs and the Issues, but can't find the official way to ensure that Signals are active - is there a fixture for that which I'm missing?

**Comment by pelme** [comment]
The proper location is `ready()` in your app. See the note Django's signal documentation in "Where should this code live?":
https://docs.djangoproject.com/en/1.10/topics/signals/#connecting-receiver-functions

pytest-django will call `django.setup()` which will in turn invoke `ready()`.

**Comment by jamescooke** [comment]
Thanks for the reply. I refactored the code to remove my work around (import signals) and solve the problem exactly as you mention (https://github.com/jamescooke/prlint/commit/aaa77e0547c68c659092273c15d98bd4ede775ae) but I wasn't sure what the do with this Issue.

The reason for my confusion was that originally these tests passed using Django's `TestCase` and runner. If I'd developed it from scratch on pytest, then I wouldn't have found this issue.

Thanks :+1:
