### ISSUE TITLE
Settings fixture + Celery

### ISSUE THREAD

**Issue by dbrgn** [pytest-dev/pytest-django#46]
I'm trying to update the settings for Celery using the settings fixture (CELERY_ALWAYS_EAGER=True). But somehow celery fetches its settings before I get to the point where I update them, so changing the settings fixture has no effect.

This used to work with the Django test class: https://docs.djangoproject.com/en/dev/topics/testing/overview/#overriding-settings

Is there a fix or workaround to this problem?

**Comment by pelme** [comment]
I'm closing this in favor of #136 which tracks the improvements to the settings fixture.
