### ISSUE TITLE
Testing user permissions fail

### ISSUE THREAD

**Issue by alorence** [pytest-dev/pytest-django#462]
Hi,

In a test, I want to ensure a user can't access a particular object by default, then after setting right permissions on this user, verify he can now access the resource. This test fail, but I can't find why.

I reproduced this issue with the most minimal example:

```python
@pytest.mark.django_db()
def test_user_has_perm(django_user_model):
    # Create a new user
    john_doe = django_user_model.objects.create_user(username='johndoe', email='jd@example.com', password='123456')

    # Get or create the permission to set on user
    user_ct = ContentType.objects.get(app_label='auth', model='user')
    p, created = Permission.objects.get_or_create(content_type=user_ct, codename='delete_user', name="Can delete user")

    assert created is False
    # User don't have the permission
    assert john_doe.has_perm(p) is False

    # Set permission to user
    john_doe.user_permissions.add(p)
    assert john_doe.has_perm(p) is True  # ---> FAIL, why ?
```

To help finding the reason, I created an example repository, with almost nothing else than pytest and django environment: see https://github.com/alorence/pytest_issue and the corresponding travis: https://travis-ci.org/alorence/pytest_issue

I don't know if I misused the django_db mark. I also tried to pass db as a fixture, or use transaction=True in django_db mark, with no luck.

Can you help me to find what is wrong in this example ?

Note: I also posted the question on [SO](http://stackoverflow.com/q/42220272/1887976), if you want to earn some points ;)

**Comment by alorence** [comment]
Ok, I found my mistake. I had to re-query the user before testing the permission has been set. This is because of [permission caching](https://docs.djangoproject.com/en/dev/topics/auth/default/#permission-caching)

```
    # User don't have the permission
    assert john_doe.has_perm('auth.delete_user') is False

    # Set permission to user
    john_doe.user_permissions.add(p)

    # Because permissions are 'cached'
    # See https://docs.djangoproject.com/en/dev/topics/auth/default/#permission-caching
    assert john_doe.has_perm('auth.delete_user') is False

    # After re-querying the user, it works !
    john_doe2 = User.objects.get(username='johndoe')
    assert john_doe2.has_perm('auth.delete_user') is True
```

**Comment by jamescooke** [comment]
@alorence Glad you found the bug. You can also use `refresh_from_db` for the purpose of reloading: https://docs.djangoproject.com/en/1.10/ref/models/instances/#refreshing-objects-from-database

**Comment by alorence** [comment]
Thank you for the tip, I will test it ASAP 👍

**Comment by alorence** [comment]
Unfortunately, refresh_from_db() doesn't work in this case.

From [doc](https://docs.djangoproject.com/en/1.10/topics/auth/default/#permission-caching):

> If you are adding permissions and checking them immediately afterward, in a test or view for example, the easiest solution is to re-fetch the user from the database

and

```
# Request new instance of User
# Be aware that user.refresh_from_db() won't clear the cache.
user = get_object_or_404(User, pk=user_id)
```

**Comment by jamescooke** [comment]
Thanks @alorence - I did not know that :smile:
