### ISSUE TITLE
Update setuptools_scm-1.11.1 requirement or unpin

### ISSUE THREAD

**Issue by stephanema** [pytest-dev/pytest-django#465]
I have a little question:
Do you really need a hard dependency to setuptools_scm-1.11.1.tar.gz?
  
I have some packages which needs setuptools_scm-1.15.0.tar.gz and collide with this.
  
Actually I do the following:

1. install setuptools_scm-1.11.1.tar.gz
2. install pytest-django-3.1.2.tar.gz
3. install setuptools_scm-1.15.0.tar.gz
  
I am on a win7 64bit pc with python 3.5.3 64bit *without* internet connection.
  
Actually all my pytest’s with django works well.
  
If it’s not a problem for you, could you put the dependency to 
setuptools_scm-1.15.0 Or setuptools_scm only?

**Comment by blueyed** [comment]
I think we can upgrade it, potentially also unpinned (or with a minimum version).
Can you create a PR for it, please?

**Comment by pelme** [comment]
Unpin or setting a minimum version is fine by me unless CI fails. PR welcome!
