### ISSUE TITLE
Documentation TOC display/layout issue

### ISSUE THREAD

**Issue by fmoor** [pytest-dev/pytest-django#475]
The following page does not render properly in chrome. Some of the items in the table of contents flows over into the body of the page.

http://pytest-django.readthedocs.io/en/latest/helpers.html?highlight=client
chrome: 57.0.2987.133
Windows: 8.1

![image](https://cloud.githubusercontent.com/assets/8278635/25154300/fe8d5162-2444-11e7-906b-3218ec0c9071.png)

**Comment by blueyed** [comment]
Thanks for the report.  Also applies to Firefox.

**Comment by bluetech** [comment]
Seems fine now, let us know if not.
