### ISSUE TITLE
live_server fixture does not see database updates

### ISSUE THREAD

**Issue by mpasternak** [pytest-dev/pytest-django#489]
Hi, 

it looks like live_server process does not see my database updates. 

I'm using either PostgreSQL or an in-memory SQLite 3, does not matter. 

I want to be able to change the database from inside my test function and to make live_server see the change. 

Is there anything special I should do? 

I've tried adding transaction_db fixture to my test functions, does not mater.

**Comment by blueyed** [comment]
Can you provide a minimal test case?
What about providing it as a PR then also?

**Comment by mpasternak** [comment]
I understand that this is not intended behavior. In this case I'll work on a better report and probably a pr. Thanks.

**Comment by blueyed** [comment]
> I want to be able to change the database from inside my test function and to make live_server see the change.

How do you do that?

**Comment by mpasternak** [comment]
Looks like it is a problem with my environment because I can't replicate it in an example app. If anything changes in this terms I'll reopen. Thanks

**Comment by mpasternak** [comment]
This was a problem with my code. Whew.
