### ISSUE TITLE
Does pytest-django know about [tool:pytest]?

### ISSUE THREAD

**Issue by lwm** [pytest-dev/pytest-django#494]
According to https://docs.pytest.org/en/latest/customize.html:

> Note that an existing pytest.ini file will always be considered a match, whereas tox.ini and setup.cfg will only match if they contain a [pytest] or [tool:pytest] section, respectively.

I was having trouble getting my options picked up with `[tool:pytest]` and not just `[pytest]`. Does pytest-django know what to do with `[tool:pytest]`? Will submit a PR if this needs work.

**Comment by blueyed** [comment]
`[tool:pytest]` in `setup.cfg` should work.

See https://github.com/pytest-dev/pytest-django/blob/7581b9f059cf78ab35625ded8cd150d659e6c60d/setup.cfg#L1-L5 ;)

**Comment by blueyed** [comment]
What option and what file have you tried?

**Comment by blueyed** [comment]
Found https://github.com/giving-a-fuck-about-climate-change/carbondoomsday-django/pull/13/commits/deee5ece018ecd919f7ba67636c8565935d24f9c, but there it's not about pytest-django options at all?!

**Comment by blueyed** [comment]
Maybe using `pytest -c setup.cfg` is problematic?

**Comment by lwm** [comment]
Ah, very good! Thanks. I'm not really sure ... but closing here for now.

**Comment by blueyed** [comment]
Please let us know in case using `-c` is causing this confusion, i.e. it should still use `[tool:pytest]` of course etc.
