### ISSUE TITLE
How can I use Django's built-in TestCase methods

### ISSUE THREAD

**Issue by guyjacks** [pytest-dev/pytest-django#510]
For example, how would I call assertQuerysetEqual?

**Comment by blueyed** [comment]
See https://github.com/pytest-dev/pytest-django/pull/232.

**Comment by guyjacks** [comment]
I'm interpreting the discussion in #232 as saying this feature is not currently implemented.  Am I correct?

**Comment by blueyed** [comment]
Yes, it is not merged yet - I've just looked it up.
Would be nice if somebody would pick it up again.

**Comment by blueyed** [comment]
Closing this in favor of #232.
