### ISSUE TITLE
admin_client is not checking for login success

### ISSUE THREAD

**Issue by p-himik** [pytest-dev/pytest-django#513]
`client.login` inside `admin_client` can return `False` in the case when there's an existing admin user with a password set to something other than `'password'`. Perhaps, `admin_client` should use `force_login` instead?

**Comment by blueyed** [comment]
Seems sensible
Can you provide a failing test and fix in a PR?

**Comment by p-himik** [comment]
Sure, I'll do that in the next couple of days.
