### ISSUE TITLE
How can I pass extra Django arguments?

### ISSUE THREAD

**Issue by legshort** [pytest-dev/pytest-django#516]
I would like to pass `--exclude-tag` argument with pytest-dango.
However, the only way I found is that using [TestRunner](http://pytest-django.readthedocs.io/en/latest/faq.html#how-can-i-use-manage-py-test-with-pytest-django).

Is there any way that I can pass Django arguments?

**Comment by blueyed** [comment]
I think you have to use `PytestTestRunner` then, yes.

**Comment by legshort** [comment]
I will try to take a look, thanks!!
