### ISSUE TITLE
No module named TestCommon

### ISSUE THREAD

**Issue by dan-klasson** [pytest-dev/pytest-django#519]
I'm getting below when running `pytest`. I'm using `pytest-django-3.1.2`

    (foo) dan@dan-laptop:~/foo/django$ pytest
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.12, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
    Django settings: unreal.settings.dev (from ini file)
    rootdir: /home/dan/foo/django, inifile: pytest.ini
    plugins: django-3.1.2
    collected 455 items / 1 errors                                                  

    ==================================== ERRORS ====================================
    _ ERROR collecting node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py _
    ImportError while importing test module '/home/dan/foo/django/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    node_modules/node-gyp/gyp/pylib/gyp/generator/ninja_test.py:13: in <module>
        import TestCommon
    E   ImportError: No module named TestCommon
    !!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
    =========================== 1 error in 8.35 seconds ============================
    (foo) dan@dan-laptop:~/foo/django$

**Comment by blueyed** [comment]
You can use `testpaths` in pytest's config to specify the location of your tests.
This prevents this, and speeds up collection.
