### ISSUE TITLE
pytest.mark.django_db doesn't play nice with setup_module()

### ISSUE THREAD

**Issue by Suor** [pytest-dev/pytest-django#53]
Here is my test code:

``` python
import pytest
pytestmark = pytest.mark.django_db

from handy.db import do_sql, fetch_val

def setup_module(fetch_val):
    print 1
    do_sql('''
        create table test (
            id int primary key,
            tag int not null
        );

        insert into test values (1, 10), (2, 20);
    ''')
    print 2

def test_fetch_val():
    print 3
    assert fetch_val('select min(id) from test') == 1
```

And I get `DatabaseError: relation "test" does not exist` from `test_fetch_val()`. I also get

```
1
2
Creating test database for alias 'default'...
3
```

captured output. Looks like `setup_module()` is called before database is created.

**Comment by rinatio** [comment]
@pelme 
With the `db` fixture it is possible to run such setup on function scope only, not on class, module or session. For example if we need to fill in some records into database before class tests executed.

```
==================================== ERRORS ====================================
___________ ERROR at setup of TestHistoryAlerts.test_one_point_data ____________
ScopeMismatch: You tried to access the 'function' scoped fixture 'db' with a 'session' scoped request object, involved factories
tests/conftest.py:140:  def ts(db)
../../../../.virtualenvs/app/lib/python2.7/site-packages/pytest_django/fixtures.py:158:  def db(request, _django_db_setup, _django_cursor_wrapper)
```

Is there any other way to handle it?

**Comment by pelme** [comment]
Yes, that is a limitation of the db fixture as it is currently implemented. In PR #258 there has been some work towards making it possible to create database state that is bound by class/module/session scope.

**Comment by slykar** [comment]
Even tough this issue is pretty old, I've found it useful to figure out the issue I was having with `pytest` and `pytest-django`. Since `pytest 3.5.0` there's an issue when using `django_db` mark and `module` level fixtures.

Below was working before `3.5.0` (at least it wasn't causing any issues).

```python
@pytest.fixture(scope='module')
def user():
    return User.objects.create(...)

@pytest.mark.django_db
def test_some_case(user):
    pass
```

After `3.5.0` it raises

```
Failed: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```

The solution was to remove `scope='module'`.

**Comment by mahadi** [comment]
+1 For me, just switching from some initial Djano unit tests, this is a major drawback, when initializing the database for my API test cases. Actually supporting session/module database fixtures should be a basic feature. Any suggestions how to solve this?
