### ISSUE TITLE
Parameterizing django settings across all tests

### ISSUE THREAD

**Issue by mo-mughrabi** [pytest-dev/pytest-django#539]
Hello everyone, 

This is more of a question than an issue, am working on building reusable applications that would allow us to use in different projects. For that, we are using pytest and pytest-django to run all tests in django, at the moment most tests uses parameterized tests so we can pass different django settings and validate the tests accordingly. 

As described this means that we had to explicitly define the parameteized testing for each test case. Hence, am looking for a way to cause pytest to run the entire tests using different settings as parameterized values for each test. 

```
def pytest_generate_tests(metafunc):
    # if 'stringinput' in metafunc.fixturenames:
    if 'settings' in metafunc.fixturenames:
        metafunc.parametrize(
            'settings',
            list_of_settings,
            scope='session'
        )
```

I used something similar to the above to pass different settings to tests, but this also means we should define a `settings` in each test case. 

Is there any recommended way we can do that without having to go through all tests and make sure `settings` fixture is present? 

Thanks, 

FYI @mou55

**Comment by mou55** [comment]
I don't know a way to not pass fixtures arg(s) to test functions using it

**Comment by mo-mughrabi** [comment]
Closing this question, as further reading docs I realized there is better way of doing that.. here is what we did 

```
# conftest.py
@pytest.yield_fixture(params=available_backends)
def settings(request, settings):
    if request.param not in available_backends:
        raise ValueError('auth_backend {} not implemented.'.format(request.param))
    wrapper = SettingsWrapper()
    settings.DJANGO_PROFILE_AUTH_BACKEND = request.param
    yield wrapper
    wrapper.finalize()

# setup.cfg
usefixtures = settings
```

Above will enforce setting for every test, it was mentioned in the documentation [here](https://docs.pytest.org/en/latest/fixture.html#scope-sharing-a-fixture-instance-across-tests-in-a-class-module-or-session)
