### ISSUE TITLE
Support for Django >=1.9  parallel test run

### ISSUE THREAD

**Issue by noamelf** [pytest-dev/pytest-django#545]
Hi,
Thanks for creating this plugin!
We are using it in our project, and tried using the parallel run option (with xdist), but didn't see much improvement. We just saw that newer Django versions (>=1.9) also has [parallel run option](https://docs.djangoproject.com/en/1.10/ref/django-admin/#cmdoption-test-parallel), and were wondering whether it will have better results.  Is there a way to use Django test parallelism with this plugin (we didn't see any in the docs).

Thanks!

**Comment by blueyed** [comment]
There is no support for using this, but I assume it will not differ much from pytest-xdist (on a single computer).
However, using pytest-xdist on multiple remote hosts (where each has its own DB container) brings a huge boost for my project.

**Comment by romanivanyushchenko** [comment]
This is very interesting, the documentation says that "can lead to significant speed improvements on multi core / multi CPU machines" https://pytest-django.readthedocs.io/en/latest/usage.html#running-tests-in-parallel-with-pytest-xdist

**Comment by bluetech** [comment]
xdist is pytest's solution to this, it's highly unlikely we'll add specific support for something else in pytest-django.
