### ISSUE TITLE
DATABASES 'TEST' setting is ignored by pytest-django

### ISSUE THREAD

**Issue by min0ru** [pytest-dev/pytest-django#559]
Django allows you to specify different database for testing purpose. It is done by adding 'TEST' section in your settings.py. 

For example:

```
DATABASES = {
    'default': {
        #....
        'NAME': 'main_db_name',                       
        'TEST': {
            'NAME': 'test_db_name',
        }
    }
}
```

So when you are running ./manage.py test then 'test_db_name' will be used.

When you are running pytest with pytest-django plugin with unmodified django.unittest tests this option is ignored. Pytest is trying to use 'test_main_db_name' prior to 'test_db_name' which differs with default Django behavior. That could be confusing due to pytest-django docs statement "Easy switching: Existing unittest-style tests will still work without any modifications." 

This can be reproduced on:
pytest==3.3.1
pytest-django=3.1.2

**Comment by blueyed** [comment]
That would be a (severe) bug, but I have not seen this myself.

Is it still an issue for you, and can you provide more information and/or a failing test for pytest-django?

**Comment by roma-guru** [comment]
Seems to be still ignored...

**Comment by merwok** [comment]
Can you provide more information and/or a failing test for pytest-django?

**Comment by bluetech** [comment]
Closing as needs-info, can reopen if more details are provided.

**Comment by merwok** [comment]
Can you confirm that your settings example works with vanilla django tests?

From https://docs.djangoproject.com/en/3.1/topics/testing/overview/#the-test-database
>  The TEST dictionary in DATABASES offers a number of settings to configure your test database. For example, if you want to use a different database name, specify NAME in the TEST dictionary for any given database in DATABASES.

I read that to mean `DATABASES = {"default": ..., "TEST": ...}`, not testing `TEST` inside `default`.

**Comment by abreumatheus** [comment]
This is still an issue to this date.

**Comment by merwok** [comment]
Without detailed information (see questions in previous messages), it’s hard to understand the problem to help fix it.
