### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by elcolie** [pytest-dev/pytest-django#561]
In the Django official docs. It has `reset_sequence` feature 
But I do not found it in `pytest-django` docs

How can I achieve same thing in `unittest`?

**Reference:**
https://docs.djangoproject.com/en/2.0/topics/testing/advanced/#django.test.TransactionTestCase.reset_sequences

**Comment by sliverc** [comment]
This feature had been started in https://github.com/pytest-dev/pytest-django/pull/308 but was unfortunately never finished. It would be great if some could pick it up.
