### ISSUE TITLE
db argument

### ISSUE THREAD

**Issue by elcolie** [pytest-dev/pytest-django#571]
I copy&paste the code form my colleague, he did not say anything just show me the way how to use `fixture` in `pytest` Without it raises

Now I would like to ask question about this error.
To reproduce this error just omit `db` in the function belows
```bash
Failed: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```

```python
@pytest.fixture
def social_whitelist(db):
    Whitelist.objects.bulk_create([
        Whitelist(address='204.15.20.0/22'),
        Whitelist(address='2a03:2880:f23f::/48'),
    ])
```

Where is the doc about `db` argument in for my django fixture?

**Comment by bluetech** [comment]
The doc is here: https://pytest-django.readthedocs.io/en/latest/database.html#enabling-database-access-in-tests
