### ISSUE TITLE
Add pytest to requirements.txt...

### ISSUE THREAD

**Issue by ptressel** [pytest-dev/pytest-django#581]
It would be a kindness to projects using pyteste-django if pytest (which is a direct dependency for pytest-django) could be added to requirements.txt.  Otherwise, pip / pipenv can't infer the dependency graph, and projects using pytest-django must themselves add pytest *before* pytest-django in their own dependencies.  Thanks!  Details in this PR: pytest-dev/pytest-django#579

**Comment by blueyed** [comment]
Commented on https://github.com/pytest-dev/pytest-django/pull/579.

**Comment by blueyed** [comment]
Closing in favor of https://github.com/pytest-dev/pytest-django/pull/579 - still missing information there though.
