### ISSUE TITLE
'FixtureRequest' object has no attribute 'get_host'

### ISSUE THREAD

**Issue by stuaxo** [pytest-dev/pytest-django#582]
I was trying to do some testing in Wagtail, using the middleware there, which calls get_host on request, this failed because get_host doesn't seem to be implemented on pytest-djangos flavour.

This is the function I'm trying to call using pytests request:

https://github.com/wagtail/wagtail/blob/d483c8d46543cd75caac8d8b4067173646072c81/wagtail/core/models.py#L95

**Comment by blueyed** [comment]
Please provide an example, especially the code to build your `request`.
Looks like you use `request`, which is a pytest fixture.
In pytest-django, please use `rf`.
