### ISSUE TITLE
Settings module cannot use environment variables set in pytest.ini

### ISSUE THREAD

**Issue by anlutro** [pytest-dev/pytest-django#583]
Given the following `pytest.ini`:

```
[pytest]
DJANGO_SETTINGS_MODULE = example.settings.dev
env = DJANGO_SECRET_KEY=InsecureTestKey
```

and a settings module file which contains this:

```python
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
```

running pytest fails because the environment variable is not set at the time pytest (indirectly?) imports the settings module.

One obvious solution is to just require developers to set the environment variables themselves before running the tests, but that's something I'd like to avoid.

We could also rewrite our settings module to never *require* environment variables to be set, but I do prefer the code to fail early if required environment variables aren't set.

I'm not sure if this is even possible to solve with the pytest plugin system.

**Comment by little-gui** [comment]
I believe that adding extra env vars its impossible within pytest.ini, but I found a plugin that does it and it uses the same syntax your file has:
https://github.com/MobileDynasty/pytest-env

**Comment by blueyed** [comment]
@anlutro 
Are you using that plugin?

**Comment by anlutro** [comment]
Hey! It's been so long that I can't really remember. I will find time this weekend to try and reproduce this.

**Comment by anlutro** [comment]
Okay so yes, I was using pytest-env, but I can't reproduce the issue now so I'll just close this. Sorry for the trouble!
