### ISSUE TITLE
New release compatible with Django 2.0.

### ISSUE THREAD

**Issue by felixxm** [pytest-dev/pytest-django#585]
I will be grateful for a new release that will support Django 2.0. If you need any help, I volunteer.

**Comment by blueyed** [comment]
What is missing for compatibility?
(It works for us already)

Otherwise there is #473 already, but I haven't found the time.

**Comment by felixxm** [comment]
Sorry, I missed #473. Everything works fine :+1: , but I think it will be good to add a new release with official Django 2.0 support instead of using current master branch.

**Comment by blueyed** [comment]
We're using the release at work - so again: what is missing?  Something in the meta data only?
