### ISSUE TITLE
Question on database in case of xdist and TestCase based django tests

### ISSUE THREAD

**Issue by valignatev** [pytest-dev/pytest-django#602]
Hi! It's not really a bug report, it's more of a question.

Docs say that `pytest-django` works with `pytest-xdist` correctly, but only if we use its db marks and fixtures. I wasn't able to find out explicit information on whether `pytest-xdist` will work correctly if I run it with django `TestCase`-based tests. Brief experiments and looking through the code show me that it won't.
I also found #545 which asks for native Django parallel run support.

So my question is: Do `TestCase`-based tests share the same database, if being run with xdist?

UPDATE: also, I probably should mention that I'm using in-memory SQLite database for testing. Comments in django database creation tell me that "Forking automatically makes a copy of an in-memory database", but database name is the same for all tests: `file:memorydb_default?mode=memory&cache=shared`, so I'm not sure.

**Comment by blueyed** [comment]
Test databases use different suffixes, but that might not work with in-memory DBs.
See https://github.com/pytest-dev/pytest-django/blob/7d5b2d9cc8f8b8eca2fa501214d2158eeb3ab6d1/docs/usage.rst#running-tests-in-parallel-with-pytest-xdist, and https://github.com/pytest-dev/pytest-django/blob/7d5b2d9cc8f8b8eca2fa501214d2158eeb3ab6d1/pytest_django/fixtures.py#L44.

**Comment by blueyed** [comment]
> Brief experiments and looking through the code show me that it won't.

Please also elaborate on this.
What is not working?

**Comment by valignatev** [comment]
Hi! Thanks for the response. When I created an issue, I was under impression that parallel tests should use a shared database, but it's not the case, and I understood that by reading pytest-django and Django source code. Now I understand that my question doesn't make much sense, so I'm closing it.
