### ISSUE TITLE
'ignore_template_errors' not a registered marker

### ISSUE THREAD

**Issue by jamesbeith** [pytest-dev/pytest-django#609]
I tried to use the `ignore_template_errors` marker...

```
import pytest

@pytest.mark.ignore_template_errors
def test_foo():
    pass
```

but running the tests resulted in the following error...

```
AttributeError: 'ignore_template_errors' not a registered marker
```

When I run `pytest --markers` to see which markers exist for the test suite `ignore_template_errors` is not listed, but the `django_db` and `urls` markers from `pytest-django` are.

```
$ pytest --markers
@pytest.mark.webtest
@pytest.mark.django_db(transaction=False)
@pytest.mark.urls(modstr)
@pytest.mark.skip(reason=None)
@pytest.mark.skipif(condition)
@pytest.mark.xfail(condition, reason=None, run=True, raises=None, strict=False)
@pytest.mark.parametrize(argnames, argvalues)
@pytest.mark.usefixtures(fixturename1, fixturename2, ...)
@pytest.mark.tryfirst
@pytest.mark.trylast
```

I do not have `markers` declared in my `setup.cfg` file but do include `--fail-on-template-vars` in `addopts`.

```
pytest-django==3.2.1
pytest==3.6.1
```

**Comment by blueyed** [comment]
Thanks for the report, https://github.com/pytest-dev/pytest-django/pull/610 should fix it.
