### ISSUE TITLE
pytest should not require manage.py

### ISSUE THREAD

**Issue by nitely** [pytest-dev/pytest-django#639]
There is no reason for this. No test runner should require a real django project. Just set the settings and setup django. Otherwise we get:

```
pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
```

when running standalone libraries on CI.

**Comment by blueyed** [comment]
It is only meant as a helper.
You can ignore this using "django_find_project = False", but then need to ensure that the project is importable, e.g. by using `python -m pytest` or using `PYTHONPATH`.

**Comment by nitely** [comment]
A django test runner does not need any of that. Why would pytest need it?. Adding a project to `PYTHONPATH` may generate buggy programs pretty hard to debug (like double imports -> i.e django signals gettings registered twice, etc).

A django runner looks like this:

```python
import django
from django.test.runner import DiscoverRunner

os.environ['DJANGO_SETTINGS_MODULE'] = 'project.project.settings.test'


def run_tests():
    test_runner = DiscoverRunner()
    failures = test_runner.run_tests([])
    sys.exit(failures)

if __name__ == "__main__":
    django.setup()
    run_tests()
```

**Comment by pelme** [comment]
This was the most common problem people had when adopting pytest-django for their django projects. I tried to convince people for years to use setup.py / proper installs in talks, tutorials and FAQs but this issue kept coming up all the time.

The most common use case (in my experience) is to use pytest-django with projects. Django itself has not really promoted proper Python-packaging of projects which leads to people being confronted with this problem when trying out pytest. This makes switching to pytest more painful than it needs to be.

If you develop a Django library, you surely have `setup.py`/a package/`pip install -e .`-setup  or similar. Dealing with that situation is documented at: https://pytest-django.readthedocs.io/en/latest/managing_python_path.html#managing-the-python-path-explicitly

Unfortunately your use case requires a bit more work (setting `django_find_project = False`) but it makes it easier for projects. :)

**Comment by blueyed** [comment]
See also https://github.com/pytest-dev/pytest-django/issues/599#issuecomment-415551601.

**Comment by nitely** [comment]
@pelme that does not sound right. Even a django project does not *need* `manage.py`. Runing the above code on a django project and printing `sys.path` on a test shows:

```python
# First path is the script working dir (i.e the django project were the manage.py usually is)
[
    '/home/xxx/Spirit2',
    '/home/xxx/venv35/lib64/python3.6/site-packages/setuptools-18.1-py3.6.egg',
    '/home/xxx/venv35/lib64/python3.6/site-packages/pip-7.1.0-py3.6.egg',
    '/usr/lib64/python36.zip',
    '/usr/lib64/python3.6',
    '/usr/lib64/python3.6/lib-dynload',
    '/home/xxx/venv35/lib64/python3.6/site-packages'
]
```

So django is not messing with the pythonpath or anything. All that's needed is setting the `DJANGO_SETTINGS_MODULE` env-var and calling `django.setup()` to initialize django, then the test runner just collects all tests (on child dirs) and runs them. I don't see why pytest would be any different, but I guess I'll have to dig the code and see what's going on.

**Comment by pelme** [comment]
I don't like `manage.py` either. I always *remove* `manage.py` and configure the paths via `setup.py`/`pip install -e .` in my own projects and have preached that way of working for in conference talks etc. :)

Django does not mess with `PYTHONPATH` directly. However the path where a Python script is located will automatically be added to sys.path. Just by running `python manage.py` or `./manage.py` the directory of the `manage.py` script will be on Python path and enable imports. This is the fact that a lot of people rely on in Django projects. They are then surprised that running `pytest` does not work even though they haven't realized they have not had a proper and explicit python path configuration ever.

We're on the same side, I wish everyone knew how pip and editable installs but I think that is a bigger change that needs to take place in the Django community. :)
