### ISSUE TITLE
pytest-django: No such database error

### ISSUE THREAD

**Issue by donalg007** [pytest-dev/pytest-django#640]
I need to understand how pytest-django creates the test database. 

I understood that the default behaviour for pytest-django is to create the test database by applying migrations and remove the database after the test run.

I have NO conftest.py file just a pytest.ini as follows:

```
DJANGO_SETTINGS_MODULE = myproject.test_settings
python_files = tests.py test_*.py *_tests.py
```
I get an error saying:

`E       OperationalError: ERROR:  No such database: test_database
`

If I create a conftest.py to point to my existing database, my tests all run fine.

My question is - how can I avail of pytest-django default behaviour? What do I need apart from my pytest.ini shown above?

I want pytest-django to:

- Look at settings in pytest.ini
- Create a test database
- Run migrations
- Run tests
- Drop the database

Version Info:

```
Python 2.7 
Django 1.11.12
djangorestframework
Version: 3.8.2
```

test_settings.py in my project

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'test_digitex',
        'USER': 'digitex',
        'PASSWORD': 's1dthesex1sttest',
        'HOST': 'localhost',
    }
}
```

```
psql --version
psql (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg16.04+1)
```
Any help greatly appreciated.

**Comment by blueyed** [comment]
It should come from your `myproject.test_settings`.

Normally you would have e.g. `myproject.settings` and then e.g. `test_settings` which imports everything from there, but configures some things differently.
DATABASES should not be among those things though, since Django prefixes your existing DB with `test_`.

Closing this as answered, but feel free to follow up - nothing pytest-django specific though, but rather basic Django stuff.

**Comment by donalg007** [comment]
thanks appreciate the response

**Comment by bernadetteguinan** [comment]
I just want to follow up on this issue.

- I have a Django project with a settings.py file
- I add settings.py to my pytest.ini
- I have NO conftest.py yet and I am NOT pointing pytest  to the existing database

```
[pytest]
DJANGO_SETTINGS_MODULE = myapi.settings
python_files = tests.py test_*.py *_tests.py
```

What is the default behaviour of pytest? Does it internally do the following:
1. Create a test database
2. Apply all migrations
3. Run Tests
4. Remove the test database

Is this correct? 

I ran this command
`pytest -v -s`

And I got the following error:

```
E       OperationalError: ERROR:  No such database: test_myappdb

../venv/local/lib/python2.7/site-packages/psycopg2/__init__.py:130: OperationalError
```

Here is the database section of my settings.py

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'myappdb',
        'USER': 'myappdb',
        'PASSWORD': 'mypassword',
        'HOST': 'localhost',
    }
}
```

Can you give me any insights here? Thanks for your help so far!

**Comment by blueyed** [comment]
@bernadetteguinan 
What is the full traceback?

This might happen if e.g. the user "myappdb" is not allowed to create the DB I could imagine.

Try looking into your PostgreSQL logs (with enabled query logging) to see what happens.
