### ISSUE TITLE
Assert Max Num of Queries is asserting min num of queries

### ISSUE THREAD

**Issue by danielMicallef** [pytest-dev/pytest-django#661]
`fixtures.py::django_assert_max_num_queries` is supposed to raise an exception when num of queries exceeds given `num_queries`. However this implemented the other way round.

The following change solves the issue:
```
--- a/pytest_django/fixtures.py
+++ b/pytest_django/fixtures.py
@@ -395,7 +395,7 @@ def _assert_num_queries(config, num, exact=True, connection=None):
     with CaptureQueriesContext(connection) as context:
         yield context
         num_queries = len(context)
-        failed = num != num_queries if exact else num < num_queries
+        failed = num != num_queries if exact else num > num_queries
         if failed:

```

**Comment by blueyed** [comment]
Thanks.
Can you create a PR with it, please?
And if there is no (wrong) test failing with this change, please add a new one.

**Comment by anrie** [comment]
Mh ... but the line you are quoting says that the assertion fails if the actual number of queries  (`num_queries`) exceeds the defined, maximum number of queries (`num`), which looks fine to me and explains why the test (https://github.com/pytest-dev/pytest-django/blob/master/tests/test_fixtures.py#L71) is passing and not failing. But yeah, the naming of the variables could be more explicit.

**Comment by blueyed** [comment]
Thanks, @anrie.
Created https://github.com/pytest-dev/pytest-django/pull/667 to hopefully make this more readable.
