### ISSUE TITLE
Can not use --fail-on-template-vars effectively 

### ISSUE THREAD

**Issue by wimglenn** [pytest-dev/pytest-django#685]
{{obj.something|default_if_none:"Unknown"}}

I like the `--fail-on-template-vars` feature and want to use it, however when an absent context is being explicitly handled directly in the template the plugin does not recognize this (i.e. the plugin still fails those tests). See https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#default-if-none

**Comment by blueyed** [comment]
Is `obj.something` really `None`, or non-existing?

**Comment by wimglenn** [comment]
non-existent

**Comment by blueyed** [comment]
Does Django use the default then?
The docs say:

> If (and only if) value is None, uses the given default. Otherwise, uses the value.

Does this include non-existent also?

**Comment by wimglenn** [comment]
|                     | attr is missing | attr is None | attr not None but falsey |
|---------------------|:---------------:|:------------:|:------------------------:|
|         default:"y" |       "y"       |      "y"     |            "y"           |
| default_if_none:"y" |        ""       |      "y"     |            ""            |

**Comment by blueyed** [comment]
This still looks like it is working as expected, i.e. it fails if it would render nothing.

And the following does not hold, i.e. it is not handled:

> when an absent context is being explicitly handled directly in the template

**Comment by wimglenn** [comment]
You're right. Digging deeper, I had a weird interaction with other parts of the template system, and was misunderstanding what Django was doing.  Plugin `pytest-django` is working as expected (did write [this test](https://github.com/wimglenn/pytest-django/commit/d7c35671b494d8a895e9737fe3d802491eefb40a) to convince myself, if you want it?)
