### ISSUE TITLE
Read the Docs: not updated anymore

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#699]
https://pytest-django.readthedocs.io/en/latest/changelog.html is at 3.4.4 currently.

I do not have access to its admin.

@pelme 
Can you please add me to the project, so that I could investigate?

**Comment by gillesdouaire** [comment]
Indeed, the doc would be very useful, not there since 3.4.5!

**Comment by blueyed** [comment]
I have no experience with administration of RTD (no own projects there).
Is there a way to see build logs nonetheless?
Otherwise we would / could figure it out by looking at commits that might have broken it: https://github.com/pytest-dev/pytest-django/compare/3.4.4..3.4.5

**Comment by blueyed** [comment]
List of builds: https://readthedocs.org/projects/pytest-django/builds/

**Comment by stsewd** [comment]
Hi, I think you are affected by https://docs.readthedocs.io/en/stable/webhooks.html#i-was-warned-i-shouldn-t-use-github-services

**Comment by blueyed** [comment]
@stsewd 
Thanks, looks like it.

Does anybody other then @pelme has access there?

**Comment by pelme** [comment]
Sorry about the breakage, it was indeed the problem pointed out by @stsewd .

I have fixed the webhooks and the docs are now up to date.

I've also added @blueyed as maintainer if any future issues should appear. :)

**Comment by blueyed** [comment]
Thanks!
