### ISSUE TITLE
AttributeError: 'modify_settings' object has no attribute 'wrapped'

### ISSUE THREAD

**Issue by coler-j** [pytest-dev/pytest-django#703]
I am getting the following error when doing a simple test.

Error `AttributeError: 'modify_settings' object has no attribute 'wrapped'`

This is my test:

```
class FunctionalTest(LiveServerTestCase):

    def setUp(self):
        self.browser = webdriver.Firefox()

    def tearDown(self):
        self.browser.quit()

    def test_sample_test(self):
        print(f'{self.live_server_url}/login/')
        self.browser.get(f'{self.live_server_url}/login/')
        self.assertTrue(True)
```

I am not quite sure why this is happening, but I can see the following is happening:

- `test_sample_test` seems to succeed, the browser opens and goes to the page and then closes.
- `LiveServerTestCase.tearDownClass` seems to get called twice.
- If I comment out the call to `_live_server_modified_settings.disable()` within `django.tests.testcases.LiveServerTestCase.tearDownClass` then the test "passes"
- The pytest test runner shows 6 tests found, my first 5 unit test pass fine, then test in this file shows one 'green dot' to say test passed and then and 'E' for error. So in total it looks like there is somehow 7 tests.
- I am using whitenoise for static file management, so I have tried to remove that in case it was interacting, but it did not change anything.
- I ran through the TDD book from Django last week and did not encounter this issue (on another environment though)

Stack trace from error log:

```
tp = <class 'AttributeError'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
                raise value.with_traceback(tb)
>           raise value

..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\six.py:693:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\six.py:693: in reraise
    raise value
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\six.py:693: in reraise
    raise value
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\pytest_django\plugin.py:514: in teardown
    cls.tearDownClass()
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\django\test\testcases.py:1339: in tearDownClass
    cls._live_server_modified_settings.disable()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <django.test.utils.modify_settings object at 0x0610E430>

    def disable(self):
        if 'INSTALLED_APPS' in self.options:
            apps.unset_installed_apps()
>       settings._wrapped = self.wrapped
E       AttributeError: 'modify_settings' object has no attribute 'wrapped'
```

- Django version: 2.1.7
- Geckodriver version: 0.24.0 
- Selenium version: 3.141.0
- Pytest version: 4.2.0
- Pytest-django version: 3.4.5
- Python version: 3.6.5

I explored the following issues but wasn't able to debug root cause:

https://github.com/pytest-dev/pytest-django/issues/557
https://github.com/django-compressor/django-appconf/issues/30
https://github.com/divio/aldryn-search/issues/86

**Comment by coler-j** [comment]
(I also have a SO open for this: https://stackoverflow.com/questions/54835666/attributeerror-modify-settings-object-has-no-attribute-wrapped-django-liv)

**Comment by coler-j** [comment]
https://imgur.com/a/fgeyW9t

**Comment by blueyed** [comment]
Does it also happen with the following for you?

```python
from django.test.testcases import LiveServerTestCase


class FunctionalTest(LiveServerTestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_sample_test(self):
        pass
```

If not, what is `webdriver` in your case?

Apart from that I would recomment to use pytest-style tests.

**Comment by blueyed** [comment]
The above works for me with
```
platform linux -- Python 3.7.2, pytest-4.2.0, py-1.7.0, pluggy-0.8.0
Django settings: pytest_django_test.settings_sqlite_file (from ini file)
rootdir: …/Vcs/pytest-django, inifile: setup.cfg
plugins: forked-0.2, django-3.4.7.dev8+gdff7bca
collected 1 item                                                                            

test_t.py .                                                                           [100%]
```

**Comment by blueyed** [comment]
@coler-j 
Please provide more input.

**Comment by coler-j** [comment]
Sorry @blueyed I needed to move on and that was a stopper for me, so I stopped using py.test for now on this project and am just using pure Django TestCase and am no longer having any issues.

We can close this, and if I experience it on my next project (for some reason) I will try and debug further.
