### ISSUE TITLE
INTERNALERROR> Failed: Database access not allowed

### ISSUE THREAD

**Issue by cmermingas** [pytest-dev/pytest-django#713]
I have been facing this issue:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 243, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 264, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 78, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 87, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 175, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/skipping.py", line 127, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 271, in pytest_runtest_makereport
INTERNALERROR>     excinfo, style=item.config.option.tbstyle
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/nodes.py", line 284, in _repr_failure_py
INTERNALERROR>     truncate_locals=truncate_locals,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_code/code.py", line 556, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_code/code.py", line 806, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_code/code.py", line 751, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_code/code.py", line 710, in repr_traceback_entry
INTERNALERROR>     reprargs = self.repr_args(entry) if not short else None
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_code/code.py", line 628, in repr_args
INTERNALERROR>     args.append((argname, self._saferepr(argvalue)))
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_code/code.py", line 622, in _saferepr
INTERNALERROR>     return saferepr(obj)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 72, in saferepr
INTERNALERROR>     return srepr.repr(obj)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 12, in repr
INTERNALERROR>     return self._callhelper(reprlib.Repr.repr, self, x)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 38, in _callhelper
INTERNALERROR>     s = call(x, *args)
INTERNALERROR>   File "/usr/local/lib/python3.6/reprlib.py", line 55, in repr
INTERNALERROR>     return self.repr1(x, self.maxlevel)
INTERNALERROR>   File "/usr/local/lib/python3.6/reprlib.py", line 65, in repr1
INTERNALERROR>     return self.repr_instance(x, level)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 33, in repr_instance
INTERNALERROR>     return self._callhelper(repr, x)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 38, in _callhelper
INTERNALERROR>     s = call(x, *args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 244, in __repr__
INTERNALERROR>     data = list(self[:REPR_OUTPUT_SIZE + 1])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
INTERNALERROR>     self._fetch_all()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
INTERNALERROR>     self._result_cache = list(self._iterable_class(self))
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
INTERNALERROR>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
INTERNALERROR>     cursor = self.connection.cursor()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
INTERNALERROR>     return self._cursor()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
INTERNALERROR>     self.ensure_connection()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_django/plugin.py", line 749, in _blocking_wrapper
INTERNALERROR>     "Database access not allowed, "
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/outcomes.py", line 113, in fail
INTERNALERROR>     raise Failed(msg=msg, pytrace=pytrace)
INTERNALERROR> Failed: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```

It happens when I have a FK in a model with a `default` value set via a function that looks like this:

```
def default_value():
    return ModelA.objects.get(name='foo').pk
```

It happened when I used the `django_db` mark, even if it was on an empty test and even if this was the *only* test:

```
@pytest.mark.django_db
def test_this():
    pass
```

If I comment the decorator, it wouldn't happen.

I feel the error has to do with the migrations.

Thank you!

PS: Edited to remove information that became irrelevant (see my comment below)

**Comment by cmermingas** [comment]
After opening this ticket, I decided to move forward with Django's regular `TestCase` and got a more helpful error message:

```
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
my_project.models.DoesNotExist: VerificationStatus matching query does not exist.
```

So, the `VerificationStatus.objects.get(name='foo')` instance that I am trying to use as a default doesn't exist. I staged the migrations so that this value is inserted before it's needed and the `INTERNALERROR` went away.

I am going to leave this open in case you're interested in doing something about the error message. 

Cheers!

**Comment by blueyed** [comment]
I think the problem might be that the DB is blocked while pytest is trying to make a report?
I.e. the test fails, pytest-django blocks again, and then pytest's repr triggers DB access.

Did this alone really fail?  How would a Django object be involved here?
```
@pytest.mark.django_db
def test_this():
    pass
```

**Comment by blueyed** [comment]
Ping.
A minimal test case would be appreciated.

> It happens when I have a FK in a model with a `default` value set via a function that looks like this:
> 
> ```
> def default_value():
>     return ModelA.objects.get(name='foo').pk
> ```

Can you elaborate on this?

Also: how do you run pytest?  With `--showlocals`?

From the traceback it looks like there is a test failure, isn't it?

**Comment by stardust85** [comment]
I have a reproduction scenario :) It happens when you have a data migration and it raises some unexpected exception.

**Comment by blueyed** [comment]
@stardust85 
Can you at least post a traceback, please? :)
Also details about the data migrations would be good.
The best would be to have a failing test for pytest-django itself - IIRC there are tests using migrations already, where this could be based on.

**Comment by stardust85** [comment]
Here you are: https://github.com/pytest-dev/pytest-django/pull/733 It will fail pytest immediately, so please don't merge it ;)

**Comment by sicksid** [comment]
got the same error, itwas happening to me because of a signal i added that was poorly written and it was breaking when running

**Comment by alexche8** [comment]
In my case, it was because I forgot to change database settings for testing.py from sqlite3 to postgres. So be aware of the database engine that you use too.

**Comment by blueyed** [comment]
@alexche8 
Thanks for the info.
Did you get it with an "INTERNALERROR" prefix?
Can you provide the full output from the pytest run (anonymized, shortened) for reference?

**Comment by prescod** [comment]
I had to reboot my computer to get rid of whatever underlying problem was causing this.

**Comment by blueyed** [comment]
@prescod 
That also does not help us, does it?
At least a traceback or something should be provided, otherwise it is just noise.

**Comment by prescod** [comment]
Okay, the problem came back for me. Here is the traceback:

https://gist.github.com/prescod/0b9da2a23bf43a936d0f2fd7c16f4bc0

But I don't think that's the interesting part. The interesting part is that it calls block twice and unblock once, so that it isn't properly unblocked by the time the test runs.

Here is the traceback for the FIRST time it calls block:

https://gist.github.com/prescod/a771c0707198b5ef3232808df50c3a36

And here is the traceback for the second time:

https://gist.github.com/prescod/7d546133f17590c7f1a4d5a38b11b91f

I can verify that in the second call, self._dj_db_wrapper.ensure_connection == self._blocking_wrapper . So we've got two layers of block() going on.

But it seems like perhaps under normal operation we end up with 3 levels? I don't totally understand it: the BLOCK and UNBLOCKs do not happen in clean pairs as I would expect.

But anyhow, to figure out what my real, underlying problem was, I ended up editing this file:

https://github.com/pytest-dev/pluggy/blob/master/src/pluggy/callers.py#L53

And I added this line:

        except BaseException:
            excinfo = sys.exc_info()
            print("EXCEPTION THROWN", excinfo)

In my particular case the "real" problem seemed to relate to  redis and it seemed to throw an exception 3 times. That in turn caused 3 instances of the "Database access not allowed" exception. The last of these is, I guess, what's reported on the command line.

So maybe the bug is in pluggy, not pytest-django. Maybe to do with what happens if an exception is thrown while an exception is being processed???

It is pytest-django which is giving the misleading error message, however.

Is it normal for pytest-django to block a connection which is already blocked? If not, perhaps it could give an error message about that instead of about django_db. Something semantically equivalent to:

assert self._dj_db_wrapper.ensure_connection != self._blocking_wrapper, "Code tried to block a connection which was already blocked. Perhaps a caught exception caused pytest_django to call methods out of order."

If I disable all code for blocking and unblocking then I get a fairly readable Redis error in my output.

So now I have two different techniques for finding out what the "real" problem is. I hope that helps someone, including perhaps @blueyed .

**Comment by blueyed** [comment]
@prescod 
Thanks for the info!
It would be great to have a failing test in pytest-django to replicate/reproduce/show this.. then I'd be happy to look more into fixing it from there.

**Comment by prescod** [comment]
My case involved our Redis implementation so that would have been tricky. But @stardust85 had created a branch with a migration which was easy to reproduce. You had asked him to reformat it into a "standard" test case and he hadn't gotten around to that so I did it.

https://github.com/pytest-dev/pytest-django/pull/776

https://travis-ci.org/pytest-dev/pytest-django/jobs/601585098

**Comment by blueyed** [comment]
@prescod 
That's a different issue, isn't it?  I'll comment on the PR.
As for your Redis implementation, that should/could be mocked/simulated I guess.

**Comment by blueyed** [comment]
To be clear: the error is "INTERNALERROR> Failed: Database access not allowed" in both cases, but the reasons are different.  The internal error is due to pytest not handling base exceptions (which `pytest.fail` generates) in its `saferepr()` - causing the INTERNALERROR then.  But this happens only when pytest displays some other failure already.

**Comment by blueyed** [comment]
See https://github.com/pytest-dev/pytest-django/pull/778.
Please try it - but I am a bit on the side of having the fix via pytest only, and/or using an exception not derived from BaseException for older pytest's.

**Comment by prescod** [comment]
I had pytest_django-3.6.0 installed. I replaced plugin.py with the plugin.py from #778 . 

I caused the underlying Redis problem.

Unfortunately, my symptoms did not change: Pytest still swallowed the problem and reported it as 

INTERNALERROR> Failed: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.

__exit__ is called once with my real exception and then called once with None, None, None

I hope that helps.

**Comment by blueyed** [comment]
@prescod 
Can you paste the whole traceback, please?  Which pytest version do you use?  (the best would be to have the whole run (select that test then), which includes version information then)

**Comment by blueyed** [comment]
Might want to try https://github.com/blueyed/pytest/pull/32 (the fix for pytest).
Pending for pytest in https://github.com/pytest-dev/pytest/pull/6047.

**Comment by blueyed** [comment]
Please try master - if OK I'll release it shortly then.
