### ISSUE TITLE
Why I don't need @pytest.mark.django_db?

### ISSUE THREAD

**Issue by jonbesga** [pytest-dev/pytest-django#715]
Hi, I just installed pytest-django into my project and I realized that I can run tests that try to access the database without using the decorator? Anyone could explain why? Is the [documentation](https://pytest-django.readthedocs.io/en/latest/database.html) outdated?

I run:
`pytest`

Example of one of my tests:

```
def test_my_user(django_user_model):
    me = django_user_model.objects.all().count()
    assert me == 0
```

**Comment by blueyed** [comment]
`django_user_model` pulls in / uses `db` itself: https://github.com/blueyed/pytest-django/blob/7a08fc0d180e3bcbb14159ecfeedefa03dac3f7d/pytest_django/fixtures.py#L233 :)
