### ISSUE TITLE
Base Tests for Django Models

### ISSUE THREAD

**Issue by erayerdin** [pytest-dev/pytest-django#732]
Hi everybody,

I kinda adapted myself into `pytest-django`. It is great to use Django's testing features as fixtures.

My workflow when I test models is quite close to test-driven approach. For testing a model, I simply follow these steps:

1. Create a test class for model.
2. Import target model class.
3. Test `issubclass(TargetModel, django.db.models.Model)` in `test_issubclass` method.

For a "write test first" approach, this ensures;

1. if I created `TargetModel` in Django app's `models.py`,
2. if `TargetModel` is subclass of Django's `Model`, which also ensures it is not *something else*.

This correspons to a base class like:

```python
class BaseModelTest:
    model: models.Model = None

    def test_issubclass_model(self):
        assert issubclass(self.model, models.Model)
```

So whenever I write test for a model, I simply inherit as so:

```python
class TestTargetModel(BaseModelTest):
    model = TargetModel
```

And for testing a model, I simply follow the steps below:

1. Create a test class for field.
2. Import target model class.
3. Test if the field is *nullable*.
4. Test if the field *can be blank*.
5. Test if the field has a default value, and if so, what that default value *is*.
6. Test if the field has `auto_now` set **if the field is a date and time related field**.
7. Test if the field has `auto_now_add` set **if the field is a date and time related field**.

This ensures the target field's attributes, so I can write that field to the model. It also corresponds to a base class like this:

```python
DATETIME_FIELDS = (models.DateTimeField, models.DateField, models.TimeField)

class BaseModelFieldTest:
    model: models.Model = None
    field_name: str = None

    field_type: models.Field = None
    is_null: bool = False
    is_blank: bool = False
    default_value = models.fields.NOT_PROVIDED

    is_auto_now: bool = True
    is_auto_now_add: bool = True

    @property
    def field(self):
        return self.model._meta.get_field(self.field_name)

    def test_field_type(self):
        assert isinstance(self.field, self.field_type)

    def test_is_null(self):
        assert self.field.null == self.is_null

    def test_is_blank(self):
        assert self.field.blank == self.is_blank

    def test_default_value(self):
        assert self.field.default == self.default_value

    def test_auto_now(self):
        if self.field.__class__ not in DATETIME_FIELDS:
            pytest.skip(
                f"{self.model.__name__}->{self.field_name} is not a date/time model type."
            )

        assert self.field.auto_now == self.is_auto_now

    def test_auto_now_add(self):
        if self.field.__class__ not in DATETIME_FIELDS:
            pytest.skip(
                f"{self.model.__name__}->{self.field_name} is not a date/time model type."
            )

        assert self.field.auto_now_add == self.is_auto_now_add
```

So I can write a test as such:

```python
# first I write test
class TestTargetModelFooField(BaseModelFieldTest):
    model = TargetModel
    field_name = "foo"
    field_type = models.CharField

    def test_max_length(self):
        assert self.field.max_length == 64

# then I write model
class TargetModel(models.Model):
    foo = models.CharField(max_length=64)
```

This, as you can guess, does not only tests `foo`'s `max_length`, but things like if it is null or blank etc.

So, as a rule, I write test first and then create a corresponding model. The thing is, I repeat this pattern for *almost all my projects* and simply copying and pasting [base class codes](https://hastebin.com/ocunuzipup.rb) to every darn project.

So, I thought, instead of copying this to every project, I could simply send this as a pull-request to this project, `pytest-django`.

So, reviewing the base classes above, what do you think? Would it be great if we had this code in `pytest-django`?

I opened this issue and have not written the code yet since I had some hesitations. My hesitations includes the points below:

 - This is just an approach, which also can be implementable in Django's standard testing suite. It might mean I should not send this as a PR but create a new project and support both Django's standard testing suite and `pytest-django`.
 - `pytest` is a testing tool, but it stands out with its feature named *fixtures*. This approach does not implement any *fixture*, it just utilizes plain old inheritation pattern. Currently, `pytest-django` mainly has helpers a.k.a. fixtures. This is a whole different pattern and I thought it might not be welcome in the codebase with a proper way of thinking. Because this pattern might also lead to base  classes for views, templates and other aspects of Django, model is the only one aspect of it.

So, what do you think?

1. Should I send a PR?
2. Should I create my own project both supporting Django's standard testing suite and pytest?

Looking forward for your answer.

**Comment by blueyed** [comment]
Thanks for sharing in the first place.

The idea is interesting in general, but it feels more suited to linting (https://github.com/rocioar/flake8-django), and certainly makes some assumptions (there might be reasons to not use `auto_now_add` for example).

As for using classes, I'd rather see a functional approach through fixtures indeed.

```
@pytest.fixture
def basic_model_checks():
    def inner(model):
        assert issubclass(model, models.Model)
        …

        return some_callable_for_more_checks_maybe
    return inner

def test_my_foo_model(basic_model_checks):
    from app import Foo

    basic_model_checks(Foo)
```

In general I rather dislike this kind of redirection in general however.  You are also duplicating model properties then in both the model itself and the test, which makes refactoring/changes more involving.

But it might be good to enforce checking of e.g. `__repr__` always etc.

You might just want to start creating your own pytest plugin to being with (which could depend on pytest-django).

**Comment by erayerdin** [comment]
Thanks for insights @blueyed. Then I leave closing the issue to core developers' hands.

**Comment by blueyed** [comment]
Okay - please consider following up here regardless.
