### ISSUE TITLE
`reuse-db` arg in setup.cfg isn't recognized by in pytest4.5.0

### ISSUE THREAD

**Issue by eviljeff** [pytest-dev/pytest-django#735]
In [pytest4.5.0](https://github.com/mozilla/addons-server/pull/11400) we get an [error](https://github.com/mozilla/addons-server/pull/11400) with `reuse-db` we have defined in our [`setup.cfg`](https://github.com/mozilla/addons-server/blob/master/setup.cfg#L2):
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --reuse-db
```
There was no fail under pytest4.4.2, and I couldn't see any (obvious) change in the diff between 4.5.0 and 4.4.2 that would explain why there was suddenly an incompatibility between pytest-django and pytest.  It may turn out there is a bug in pytest itself, but as `reuse-db` is defined in pytest-django I'm filing here for you to investigate further.

**Comment by blueyed** [comment]
Try git-bisecting pytest to find the commit that changed it.

**Comment by bluetech** [comment]
Looking at your repo it seems like this does not happen anymore, so closing. Let use know if it is actually still an issue.
