### ISSUE TITLE
pytest triggers deprecation warning about something I'm not even using

### ISSUE THREAD

**Issue by SHxKM** [pytest-dev/pytest-django#745]
Upon finishing my test, I get the following warnings from `pytest`:

```
======================================================================== warnings summary ========================================================================
tests/test_accounts_feeds.py::test_correct_item_types_in_feed
  /Users/user/.virtualenvs/bap_dev/lib/python3.6/site-packages/registration/auth_urls_classes.py:20: DeprecationWarning: 
  include('registration.auth_urls') is deprecated and will be
  removed in django-registration 3.0. Use
  include('django.contrib.auth.urls') instead.
  
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================================= 1 passed, 2 deselected, 1 warnings in 3.94 seconds =======================================================
```

Notice `DeprecationWarning: include('registration.auth_urls')`. I am indeed using `django-registration=2.5.x`, but I have searched all of my project's files, and nowhere do I use that include or even the string `'registration.auth_urls'`. I'm perplexed as to where this deprecation warning is coming from then.

**Comment by blueyed** [comment]
What about printing the traceback in `/Users/user/.virtualenvs/bap_dev/lib/python3.6/site-packages/registration/auth_urls_classes.py:20`?
`__import__("traceback").print_stack()`

I do not think this is an issue with pytest-django really, and likely also not with pytest.
