### ISSUE TITLE
pytest is unable to catch django's IntegrityError

### ISSUE THREAD

**Issue by vanyakosmos** [pytest-dev/pytest-django#754]
pytest is unable to catch django's IntegrityError

```python
# models.py
class A(models.Model):
    val = models.BooleanField(default=True)

class B(models.Model):
    a = models.ForeignKey(A, on_delete=models.CASCADE)
```

```python
# tests.py
from django.db import IntegrityError
import pytest

@pytest.mark.django_db
def test_integrity():
    with pytest.raises(IntegrityError):
        # using object A with id=1 before creating it 
        B.objects.create(a_id=1)
```

After running `pytest` it will show two errors for `test_integrity` function: 

- FAILURES: "DID NOT RAISE <class 'django.db.utils.IntegrityError'>"
- ERROR at teardown: "django.db.utils.IntegrityError: insert or update on table "core_b" violates foreign key constraint "core_b_a_id_2a5b83ce_fk_core_a_id"

Which is basically: "here is an error about not raising IntegrityError in test_foo, and here is an error for raising IntegrityError in test_foo, deal with it"

I can catch Integrity error w/o problems outside of pytest:

```
root@1f28fc583eed:/app# ./manage.py shell
Python 3.6.7 (default, Oct 24 2018, 22:47:56)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from core.tests import test_integrity
>>> test_integrity()
>>> exit()
```

<details><summary>pip list</summary>
<p>
```
Package             Version
------------------- ---------
apipkg              1.5
asn1crypto          0.24.0
atomicwrites        1.3.0
attrs               19.1.0
certifi             2019.3.9
cffi                1.12.3
chardet             3.0.4
codecov             2.0.15
coverage            4.5.4
cryptography        2.6.1
dj-database-url     0.5.0
Django              2.2.3
django-dbbackup     3.2.0
django-extensions   2.1.7
emoji               0.5.2
execnet             1.6.1
future              0.17.1
gunicorn            19.9.0
idna                2.8
more-itertools      7.0.0
pip                 18.1
pluggy              0.11.0
psycopg2-binary     2.8.2
py                  1.8.0
pycparser           2.19
pytest              4.5.0
pytest-cov          2.7.1
pytest-django       3.4.8
pytest-forked       1.0.2
pytest-mock         1.10.4
pytest-xdist        1.29.0
python-telegram-bot 12.0.0b1
pytz                2019.1
redis               3.2.1
regex               2019.4.14
requests            2.22.0
schedule            0.6.0
setuptools          40.4.3
six                 1.12.0
sqlparse            0.3.0
tornado             6.0.2
urllib3             1.25.3
wcwidth             0.1.7
wheel               0.32.2
whitenoise          4.1.3
```
</p>
</details>

Versions:
```
pytest: 4.5.0
django: 2.2.4
```

- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by vanyakosmos** [comment]
I've tried to wrap code into `@transaction.atomic()` like in your example, but it didn't work.

<img width="382" alt="Screen Shot 2019-08-07 at 15 27 39" src="https://user-images.githubusercontent.com/16745500/62622803-ef3b1300-b927-11e9-9abe-0ac9c21ca48d.png">

Errors are the same.

**Comment by blueyed** [comment]
@vanyakosmos 
btw: pasting code is usually preferred to screenshots.

I think you need to use `@pytest.mark.django_db(transaction=True)` then probably.  Otherwise you still have the outer atomic transaction.
You could also try to close that one before instead (since transactional tests are slow in general).

**Comment by vanyakosmos** [comment]
`@pytest.mark.django_db(transaction=True)` fixed everything. I didn't even need to add inner `@trasaction.atomic`. Thank you.

**Comment by blueyed** [comment]
For reference, this can be tested without `transaction=True` (which is slow):

```python
@pytest.mark.django_db
def test_request_integrity():
    from django.db import IntegrityError
    from django.db import connection

    B.objects.create(a_id=1)
    with pytest.raises(IntegrityError) as excinfo:
        connection.check_constraints()
    assert 'Key (a_id)=(1) is not present in table "app_a"' in str(excinfo.value)
```

Django calls this itself in `_fixture_teardown` (for all DB connections): https://github.com/django/django/blob/2c66f340bb50ed6790d839157dff64456b497a43/django/test/testcases.py#L1171-L1177

**Comment by rob-levy-minimum** [comment]
> connection.check_constraints()

I can't find any documentation about this? Is it a public-facing feature?
