### ISSUE TITLE
pytest.ini is ignored when using manage.py test with pytest-django

### ISSUE THREAD

**Issue by nvishnya** [pytest-dev/pytest-django#755]
When I run pytest with coverage from the command line I get right results.
But when I try to run it with manage.py test coverage results are wrong.
Model fields are ignored.
What I figured out, is that manage.py test ignores pytest.ini file. If I delete it tests won't fail.
It says "Django settings: seabattle.settings (from environment variable)".
But I don't have such environment variable.
If I try to run pytest from command line without pytest.ini file it fails.

Here is my runner.py:
```
class PytestTestRunner:
    def __init__(self, verbosity=1, failfast=False, keepdb=False, **kwargs):
        self.verbosity = verbosity
        self.failfast = failfast
        self.keepdb = keepdb

    def run_tests(self, test_labels):
        import pytest

        argv = []
        if self.verbosity == 0:
            argv.append("--quiet")
        if self.verbosity == 2:
            argv.append("--verbose")
        if self.verbosity == 3:
            argv.append("-vv")
        if self.failfast:
            argv.append("--exitfirst")
        if self.keepdb:
            argv.append("--reuse-db")

        argv.extend(test_labels)
        return pytest.main(argv)
```
pytest==5.0.1
pytest-django==3.5.1

**Comment by blueyed** [comment]
I assume that's from the FAQ?  https://github.com/pytest-dev/pytest-django/blob/c1bdb8d61498f472f27b4233ea50ffa2bce42147/docs/faq.rst#how-can-i-use-managepy-test-with-pytest-django

> manage.py test ignores pytest.ini file

Is that where you configure Django settings?
According to the FAQ that is not supported.

I suggest using pytest directly - which provides more options etc.

**Comment by bluetech** [comment]
Closing as answered.
