### ISSUE TITLE
Provide easy access to version info.

### ISSUE THREAD

**Issue by fermezz** [pytest-dev/pytest-django#757]
I understand [`setuptools_scm` provides programmatic access to version info](https://github.com/pypa/setuptools_scm#programmatic-usage), but I think it would be nice if we could provide easy access in here, kinda following what `pytest` is doing. I can work on a PR, although if this is not something we'd want to do, let me know!

**Comment by blueyed** [comment]
Just out of interest: what's your use case?

**Comment by fermezz** [comment]
I have a few projects still running old versions of Django which latest `pytest-django` doesn't really support, so they don't have access to newer features. The idea is to port the implementation into those projects only when running `pytest-django` with a version lower than `<some-version-of-pytest-django>` so that once we can get them updated, those feature-ports are easily identifiable and removable. At the moment there's no easy way to do that. We _could_ work around it by checking the Django version but other variables might come into play so I'm not sure that's optimal.

Does that make sense?
