### ISSUE TITLE
Python 2.7: ImportError via  _handle_import_error

### ISSUE THREAD

**Issue by gudge25** [pytest-dev/pytest-django#766]
File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pytest_django/plugin.py", line 170, in _handle_import_error

    raise ImportError(msg)

ImportError: cannot import name _uuid_generate_random

**Comment by blueyed** [comment]
Full traceback?
`_uuid_generate_random` is not from pytest-django.

The error is just trying to (hopefully) help you find the real error.

**Comment by gudge25** [comment]
thanks for reply
