### ISSUE TITLE
_pre_setup is being run twice in certain cases

### ISSUE THREAD

**Issue by lanzz** [pytest-dev/pytest-django#769]
```python
from django.test import TestCase

class TestClass1(TestCase):

    def test_method(self):
        pass

class TestClass2(TestClass1):

    def _pre_setup(self):
        print 'running _pre_setup'
        super(TestClass2, self)._pre_setup()

    def test_method(self):
        self.fail()
```
Output:
```
...
test_cleaning_debug.py .F
>>>>>>>> captured stdout >>>>>>>>
running _pre_setup
running _pre_setup
>>>>>>>> traceback >>>>>>>>
self = <test_cleaning_debug.TestClass2 testMethod=test_method>

    def test_method(self):
>       self.fail()
E       AssertionError: None

test_cleaning_debug.py:15: AssertionError
>>>>>>>> entering PDB >>>>>>>>
...
```
Note how "running _pre_setup" is being printed _twice_. This will only trigger when `--pdb` is passed to `pytest`.

Culprit is here: https://github.com/pytest-dev/pytest-django/blob/d2973e2/pytest_django/plugin.py#L527-L539
The problem is that the `debug` method has been patched in _both_ `TestClass1` _and_ `TestClass2`, so when `TestClass2.debug()` is called it will invoke its super, `TestClass1.debug`, which is _also_ patched with `_cleaning_debug`, so it will run `_pre_setup` a second time.

This is normally not an issue, but in our (very specific) case, we're doing stuff in `_pre_setup` that is not idempotent and breaks stuff when run a second time.

I'm not sure what the right thing to do here is. I'll work around it in our case, but it feels like this behaviour is wrong, so you might want to think how to fix it properly.

**Comment by blueyed** [comment]
Thanks for the report.
`debug` was not being restored.
https://github.com/pytest-dev/pytest-django/pull/771 should fix this.
