### ISSUE TITLE
`TestCase.skipTest()` skips `_post_teardown`

### ISSUE THREAD

**Issue by lanzz** [pytest-dev/pytest-django#772]
`TestCase.skipTest()` will raise a `SkipTest` exception, which is not caught in `_cleaning_debug`, so the `_post_teardown()` call is skipped. Also apparently cleanups registered with `TestCase.addCleanup()` will not be run. If setup done in `_pre_setup` needs to be undone in `_post_teardown` (or in cleanups scheduled with `addCleanup()`), that will not happen for tests skipped with `skipTest()`.

This does not apply to tests skipped with a `@unittest.skip` decorator.

For comparison, `nose` runs `_post_teardown` methods for tests skipped with `skipTest()`.

**Comment by blueyed** [comment]
Thanks for the report.
I assume this works better with Django master (3.1), where this gets handled by Django now?  (https://github.com/pytest-dev/pytest-django/pull/773)

Can you provide a failing test, similar to https://github.com/blueyed/pytest-django/blob/c023564e708b5c55b57df43776d21643d1f1f2ce/tests/test_unittest.py#L461-L489 I guess?

**Comment by blueyed** [comment]
So it's only a problem when using `--pdb` after all?
In general the finalizer gets used: https://github.com/pytest-dev/pytest-django/blob/c023564e708b5c55b57df43776d21643d1f1f2ce/pytest_django/fixtures.py#L152-L153

But is skipped explicitly in `_cleaning_debug`: https://github.com/pytest-dev/pytest-django/blob/c023564e708b5c55b57df43776d21643d1f1f2ce/pytest_django/plugin.py#L538-L540

**Comment by blueyed** [comment]
Django does the same: https://github.com/django/django/pull/7436/files#diff-5d7d8ead1a907fe91ffc121f830f2a49R272-R279

> This does not apply to tests skipped with a @unittest.skip decorator.

Interesting.  Likely because the test is not being invoked in the first place though.

**Comment by lanzz** [comment]
This might be a bigger issue with `pytest` itself, it does not run `tearDown` at all for skipped tests when running with `--pdb`: https://github.com/pytest-dev/pytest/issues/5991

**Comment by blueyed** [comment]
https://github.com/pytest-dev/pytest/pull/5996 should fix the issue in pytest.

But pytest-django would still not call `self._post_teardown` when a test is skipped: https://github.com/pytest-dev/pytest-django/blob/382c6bb4e727d37e9f4c52245ed16fd3587ae818/pytest_django/plugin.py#L534-L538

However, with pytest not calling `.debug` anymore it would only affect you when calling `.debug()` yourself.

AFAICS `_cleaning_debug` was only necessary due to the misuse in pytest itself (https://github.com/pytest-dev/pytest-django/pull/406).

**Comment by blueyed** [comment]
Not calling `_post_teardown` (the Django method) is in line with Django, but I've created https://github.com/django/django/pull/11938 to fix/address this.

**Comment by blueyed** [comment]
I believe https://github.com/pytest-dev/pytest-django/pull/782 fixes it.
Please test it, I will release it then shortly.

**Comment by blueyed** [comment]
Releasing as v3.7.0 already..
