### ISSUE TITLE
database creation not happening for LiveServerTestCase?

### ISSUE THREAD

**Issue by hjwp** [pytest-dev/pytest-django#79]
Am in Holger's py.test tutorial at the PyCon.  Thought I'd try to get py.test working on a small test repo, and it looks like `django.test.TestCase` tests are working fine, including those that need the test database, but classes from `django.test.LiveServerTestCase` seem not to be seeing the test database... 

Maybe I'm just confused?

here's the test repo:  https://github.com/hjwp/book-example/tree/chapter_07

you'll need a virtualenv built with python3, django 1.7 beta, and selenium:

    mkvirtualenv pytest-py3-superlists --python=python3
    pip install selenium pytest pytest-django https://www.djangoproject.com/download/1.7b1/tarball/

and then

    py.test lists/tests.py  # normal django tests, work fine
    py.test functional_tests.py  # liveserver tests, fail seemingly because no db

**Comment by blueyed** [comment]
In https://bitbucket.org/pytest-dev/pytest/issue/517/setup_-executed-before-all-fixtures#comment-14576060 it is mentioned that https://github.com/pytest-dev/pytest-django/commit/8a9aacbd835a49064ff8999137fa6ede34f3c520 fixes it.

@hjwp 
Please re-open if that's not the case.
