### ISSUE TITLE
Test re-ordering breaks Pytest's --failed-first and --stepwise options

### ISSUE THREAD

**Issue by callahad** [pytest-dev/pytest-django#819]
The test re-ordering introduced in response to #214 seems to execute after pytest's own `--failed-first`, `--new-first`, `--stepwise`, etc. ordering options, breaking them.

We ran across this in mdn/kuma#6531, where even with `--failed-first` pytest was running dozens of known good tests before executing the failed tests.

Removing the `pytest_collection_modifyitems` function or decorating it with `@pytest.hookimpl(tryfirst=True)` seems to resolve this, though I'm not familiar enough with pytest to know if that's an appropriate solution, or if there's something we should be doing on our end instead.

**Comment by callahad** [comment]
The function in question can be found at https://github.com/pytest-dev/pytest-django/blob/v3.8.0/pytest_django/plugin.py#L418-L439, and was added in commit 5a79fba3705376c3f89f5a9e26b8244937d61768

**Comment by blueyed** [comment]
Thanks for the report.
Can you try it with pytest master?  IIRC I've fixed something there in this regard.

**Comment by blueyed** [comment]
Thanks for the report.
Can you try it with pytest master?  IIRC I've fixed something there in this regard.

**Comment by blueyed** [comment]
Thanks for the report.
Can you try it with pytest master?  IIRC I've fixed something there in this regard.

**Comment by callahad** [comment]
I see the same issue with `pytest-5.3.5.dev399+gf77d606d4`, which is the current head of `master`

**Comment by blueyed** [comment]
Ok.  Using `@pytest.hookimpl(tryfirst=True)` then seems to be sensible.
Would you like to create a PR for this?

(I was thinking of https://github.com/pytest-dev/pytest/commit/f75f7c192586fd856dad10673cd6d1f8cce03f75, which fixed it for pytest's own tests)

**Comment by callahad** [comment]
Sure! Pull request at #820
