### ISSUE TITLE
Unexpected test order when mixing pytest / unittest tests and transactional tests

### ISSUE THREAD

**Issue by pmourlanne** [pytest-dev/pytest-django#827]
Let's say I have the following tests:
```python
import pytest
from django.test import TestCase, TransactionTestCase

@pytest.mark.django_db()
def test_function_with_db():
    ...

@pytest.mark.django_db(transaction=True)
def test_function_with_transactional_db():
    ...

class MyTestCase(TestCase):
    def test_method(self):
        ...

class MyTransactionTestCase(TransactionTestCase):
    def test_method(self):
        ...
```

I expect transactional tests, here `test_function_with_transactional_db` and `MyTransactionTestCase.test_method` to run last.

Running pytest yields:
```bash
$ pytest -v

prototype/test_prototype.py::test_function_with_db PASSED
prototype/test_prototype.py::test_function_with_transactional_db PASSED
prototype/test_prototype.py::MyTestCase::test_method PASSED
prototype/test_prototype.py::MyTransactionTestCase::test_method PASSED
```

I tried fixing this by adding a `pytest_collection_modifyitems` in my project but my custom ordering runs *before* pytest-django's ordering. So pytest-django gets the last word, and in this case it's not what I want :>

I think this can be fixed by improving on what's being done in `pytest_collection_modifyitems`, I'll try something out and hopefully open a PR.

**Comment by blueyed** [comment]
Does https://github.com/pytest-dev/pytest-django/pull/820 (in master) fix it?

**Comment by blueyed** [comment]
Anyway, it might also just not work as expected.
The code that should take care of running it like Django is https://github.com/pytest-dev/pytest-django/blob/c65dc7093f31b03bca3002ee778915d6e2692bf4/pytest_django/plugin.py#L419-L440.
(I've not investigated/looked closer at your report yet)

**Comment by pmourlanne** [comment]
I'll look at https://github.com/pytest-dev/pytest-django/pull/820 👍 

About the code yes, that's what I've been looking at, and yes it should look at classes if we want to change the behaviour :>
I've found this `pytest-django-ordering` plugin https://github.com/rlucioni/pytest-django-ordering/blob/master/pytest_django_ordering/plugin.py which kinda does what I want? I need to look a bit deeper into it.

Thank you for your quick answers :)

**Comment by pmourlanne** [comment]
#820 is going to make it so my custom ordering is applied after so yes, it should fix my current issue. I could also apply `@pytest.hookimpl(trylast=True)` to my project's `pytest_collection_modifyitems`.
This will be a fine workaround :+1: 

I still think pytest-django's behaviour could be improved, I'll keep digging for now :)
