### ISSUE TITLE
Incomplete documentation example for using manage.py test

### ISSUE THREAD

**Issue by jshields** [pytest-dev/pytest-django#837]
I think this FAQ is misleading:
https://pytest-django.readthedocs.io/en/latest/faq.html#how-can-i-use-manage-py-test-with-pytest-django

It says "It translates some of Django's test command option to pytest's" in the docstring.
However, using this example and trying to pass an arg such as `keepdb`, you get `manage.py test: error: unrecognized arguments: --keepdb`

For the example to work, using `keepdb` as an example, it needs the argument(s) added to the CLI parser:
```
    @classmethod
    def add_arguments(cls, parser):
        parser.add_argument('--keepdb', action='store_true', help='Preserves the test DB between runs.')
```
https://github.com/django/django/blob/master/django/test/runner.py#L470

**Comment by bluetech** [comment]
Well, "some" is not "all" :) But I'll add a note to reduce the confusion.

**Comment by bluetech** [comment]
Oh sorry, I confused what you are saying, you are correct.
