### ISSUE TITLE
Multiple application, multiple database - not able to access any DB other than default db

### ISSUE THREAD

**Issue by praveenelan** [pytest-dev/pytest-django#839]
Problem

I have a Django(1.8) project running 2 applications: App1, App2. Both of the applications run with their own databases: app1db and app2db, sharing the defaultdb for users and groups. I am trying to integrate pytest-django as part of the unit testing. This is where I am hitting with problem as Pytest do not support multiple databases.

My use case is I would be needing the unit tests only on app1 and I am pretty much sure I won't be needing it on app2. And I can mock my users and groups objects from defaultdb for this unit tests and I won't be needing access to defaultdb. But the problem is I always see the unit tests access the defaultdb and I don't see a way of making the app1db accessible from unit test cases. When I try to access any object form app1db, I get the following error:

```
E ProgrammingError: relation "app1_table" does not exist E LINE 1: INSERT INTO "app1_table" ("field1", "field2", "... E ^
```

Database Settings

```py
{
'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'USER': 'postgres',
    'NAME': 'defaultdb',
    'PASSWORD': 'pass',
    'HOST': localhost,
},
'app1': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': 'app1db',
    'USER': 'postgres',
    'PASSWORD': 'pass',
    'HOST': localhost,
},
"app2": {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': 'app2db',
    'USER': 'postgres',
    'PASSWORD': 'pass',
    'HOST': localhost,
},
```

How do I make my pytest just look for app1db ignoring all other DBs?

SO : https://stackoverflow.com/questions/61621853/pytest-django-multiple-application-multiple-database-not-able-to-access-any

**Comment by Valze** [comment]
Django uses your default database to save all of your models if you do not have custom database routing set up.

Testing, whether pytest or django's normal test runner, will use the default settings provided by you. Meaning, if you did not tell Django to save specific models into a different database, Django will use the default database, and so will the test runner when it performs its tests.

Read here how to set up routing and other important stuff for your use case: https://docs.djangoproject.com/en/3.0/topics/db/multi-db/

**Comment by merit-mthompson** [comment]
Django under the hood makes use of `DEFAULT_DB_ALIAS` for its test classes (TransactionTestCase, TestCase) and you could try changing that in your Django settings for your tests only via https://pytest-django.readthedocs.io/en/latest/configuring_django.html.

Then all of your tests would run against the DB defined in `DEFAULT_DB_ALIAS` only.

**Comment by mistahchris** [comment]
I have implemented this behavior in several django apps and decided I could upstream the fix. I made this PR which adds multi database support for the `db` and `transactional_db` fixtures: #896

**Comment by bluetech** [comment]
This issue is about multi-db support. I'll open a new issue about this shortly and reference this one, so closing as a duplicate.
