### ISSUE TITLE
Error with django-heroku package

### ISSUE THREAD

**Issue by gui-py** [pytest-dev/pytest-django#841]
Hi. Maybe this problem is not even part of the pytest-django project, but I'm using the "django_heroku" module import in my "settings.py" file, and when running pytest, the following error appears:

```shell
File "/home/gui/.local/lib/python3.8/site-packages/pytest_django/plugin.py", line 323, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/gui/.local/lib/python3.8/site-packages/pytest_django/plugin.py", line 174, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'django_heroku'

pytest-django found a Django project in /home/gui/python/app-reg (it contains manage.py) and added it to the Python path.
If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
```

If I don't import the django_heroku module, my test works fine.

My file pytest.ini:

```ini
[pytest]
DJANGO_SETTINGS_MODULE=app_reg.settings
python_files=test*.py *tests.py
norecursedirs = .svn .git build node_modules* .tox .pytest_cache
```
I already used "django_find_project = false" and even then it didn't work.

The alternative I did to work around this, was to create a function in my "settings.py" so as not to give an error when importing "django_heroku" module:

```python
def dj_heroku():
    try:
        import django_heroku
        django_heroku.settings(locals())
    except ImportError:
        pass
dj_heroku()
```
If someone can tell me why this problem, I appreciate :)

**Comment by Valze** [comment]
Is the error unique to pytest? Do you still get the same import error if you don't use pytest?

It might be an issue of virtual environments. Namely, your pytest virtual env doesn't have django-heroku installed and thus gives you an error while it's setting up your settings file to use for your own tests.

**Comment by bluetech** [comment]
The issue is probably as @lothemar described. If you find the issue is in pytest-django feel free to reopen.

**Comment by zeyadShapan** [comment]
Have you found a solution?
