### ISSUE TITLE
[Question] An incomprehensible question about test view .

### ISSUE THREAD

**Issue by 625781186** [pytest-dev/pytest-django#848]
## code
![image](https://user-images.githubusercontent.com/30521429/84636888-b399ae00-af27-11ea-8101-7049c9a26e63.png)

###  Both functions were successfully tested independently :
![image](https://user-images.githubusercontent.com/30521429/84637147-efcd0e80-af27-11ea-9dc0-8cc22d02f6f6.png)
![image](https://user-images.githubusercontent.com/30521429/84637157-f2c7ff00-af27-11ea-8c51-5fe734e6512f.png)

![image](https://user-images.githubusercontent.com/30521429/84637178-fbb8d080-af27-11ea-8093-186e12cb3132.png)

![image](https://user-images.githubusercontent.com/30521429/84637186-fe1b2a80-af27-11ea-86f5-2764521b0f30.png)

###  But the second one will fail when I test the whole class :
![image](https://user-images.githubusercontent.com/30521429/84637341-27d45180-af28-11ea-989e-4045c7db7827.png)

![image](https://user-images.githubusercontent.com/30521429/84637331-22770700-af28-11ea-9150-0d6bbcc1b981.png)

![image](https://user-images.githubusercontent.com/30521429/84637375-31f65000-af28-11ea-9423-96f3dad0a231.png)

I don't know why .

**Comment by 625781186** [comment]
## supplement
![image](https://user-images.githubusercontent.com/30521429/84639306-c5308500-af2a-11ea-8154-bc572b7f53a3.png)

![image](https://user-images.githubusercontent.com/30521429/84639331-d083b080-af2a-11ea-853f-9ea26a190625.png)

**Comment by 625781186** [comment]
## supplement 2 :
![image](https://user-images.githubusercontent.com/30521429/84645683-89e68400-af33-11ea-8205-2093188eded8.png)

Comment the  `# @pytest.mark.usefixtures('live_server')` , Both functions were successfully tested independently .

![image](https://user-images.githubusercontent.com/30521429/84645795-bbf7e600-af33-11ea-8a13-7e61b926c704.png)

**Comment by 625781186** [comment]
And if I use `@pytest.mark.django_db(transaction=True)` , exactly the same error occurred :

![image](https://user-images.githubusercontent.com/30521429/84646672-0f1e6880-af35-11ea-9f09-496d6e7a9bed.png)

**Comment by 625781186** [comment]
I think the same https://github.com/pytest-dev/pytest-django/issues/329

**Comment by 625781186** [comment]
https://stackoverflow.com/questions/56549271/pytest-and-django-transactional-database

I seem to have missed writing `db` , so  the database was emptied after the first test case.

**Comment by bluetech** [comment]
So the question is indeed a bit incomprehensible :grin: But it seems like you found a solution, so I'll close this. Let me know if not.
