### ISSUE TITLE
Bug like `urls` marker does not restore original urlconf

### ISSUE THREAD

**Issue by AndrewPashkin** [pytest-dev/pytest-django#85]
Hi!
I've got bug using `urls` marker which alternate urlconf with secondary urlconf - tests that runs after test using it - cant reverse urls from main urlconf.
I dont know how to correctly test this thing where one test should be launched after another, and I just created test Django project that reproduces that error:

https://github.com/AndrewPashkin/pytest_urlsconf_weird

**Comment by thedrow** [comment]
This should be closed no?

**Comment by thedrow** [comment]
Actually I think there's a regression since I see this happening in pytest-django 2.9.1 as well.

**Comment by blueyed** [comment]
@thedrow 
Can you provide more information, e.g. a failing test case?

**Comment by thedrow** [comment]
@blueyed Clone https://github.com/getdrifter/drifter-server and run the tests using tox.

**Comment by thedrow** [comment]
@blueyed Would you rather see the tests output first?

**Comment by blueyed** [comment]
@thedrow 
Sorry, I have no time for this currently.
The idea would be to have a pull request for pytest-django with some failing test and then work on a fix from there.
Especially since the external information provided by @AndrewPashkin has vanished in the meantime.

**Comment by thedrow** [comment]
I'll provide a failing test case but I already looked at it and I have no idea what the fix is.

**Comment by thedrow** [comment]
@blueyed Sorry it took me so long. See #321

**Comment by blueyed** [comment]
It looked to me like the failing test was wrong.  See https://github.com/pytest-dev/pytest-django/pull/355 for a followup, with what I think the test should look like.

I am closing this issue for now: let's continue on #355.
