### ISSUE TITLE
in docs mentioned way to get a admin_client doesn't work (helpers)

### ISSUE THREAD

**Issue by elmcrest** [pytest-dev/pytest-django#850]
as mentioned in the docs about [helpers](https://pytest-django.readthedocs.io/en/latest/helpers.html) something like the following should work, right?
It seems the client doesn't login.

```python
@pytest.mark.django_db
def test_clean_inventory_min_max(client, django_user_model):
    username = "user1"
    password = "bar"
    django_user_model.objects.create_user(username=username, password=password)
    client.login(username=username, password=password)
    client.post() # fill in formdata
    # response is the login page
```

if I change it to 

```python
@pytest.mark.django_db
def test_clean_inventory_min_max(admin_client):
    admin_client.get(reverse('admin:myapp_mymodel_add'))
    # response is authenticated as expected
```

also I didn't find a test for the first approach but I sadly don't have the time right now to work on this... still, there is a chance I might be doing something wrong.

Anyways, at least I did contribute this ;) 

Above snippets aren't tested and the first can't work without formdata.

**Comment by bluetech** [comment]
In the second example you use `admin_client` which is logged-in as a superuser. In the first example it is just a simple user. That's probably why in the first example you get a login page -- a regular user doesn't have permission to access whatever URL you are accessing.
