### ISSUE TITLE
DJANGO_CONFIGURATION not use when running pytest-django in pycharm.

### ISSUE THREAD

**Issue by aidiss** [pytest-dev/pytest-django#852]
pytest.ini looks like this

```
[pytest]
DJANGO_CONFIGURATION=Test
python_files = test_*.py
```

I also tried adding "DJANGO_CONFIGURATION=Test" to Run/Debug Configurations > Python Tests > Pytest > Environment Variables 

However it looks like django is still looking for DJANGO_SETTINGS_MODULE

   ` django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

What other information should I provide?

**Comment by Andrew-Chen-Wang** [comment]
You should specify the settings since it can't find the settings file:

```
[pytest]
addopts = --ds=config.settings.test --reuse-db
python_files = tests.py test_*.py
```

**Comment by bluetech** [comment]
Indeed, according to the django-configurations [docs](https://django-configurations.readthedocs.io/en/stable/#quickstart) it needs to find both.
