### ISSUE TITLE
Trouble in docker's services connection

### ISSUE THREAD

**Issue by Bulbashful** [pytest-dev/pytest-django#854]
I'm trying to run simple test function via pytest.
`import redis`
`r = redis.Redis(host='redis', port=6379, db=0)`
`r.set('foo', 'bar')`
As result i catch the following error:
`redis.exceptions.ConnectionError: Error -3 connecting to redis:6379. Lookup timed out`
But if run this chunk of code via django's TestCase all works fine

**Comment by alexsmartens** [comment]
I'm seeing the same error when trying to deploy my app on Heroku.
Did you solve this anyhow?

**Comment by Bulbashful** [comment]
> 
> 
> I'm seeing the same error when trying to deploy my app on Heroku.
> Did you solve this anyhow?

No

**Comment by Bulbashful** [comment]
Trouble was in using docker registry. Without it all works fine
