### ISSUE TITLE
duplicate key value violates unique constraint "pg_extension_name_index" after update pytest-xdist to 2.0.0

### ISSUE THREAD

**Issue by MuslimBeibytuly** [pytest-dev/pytest-django#860]
pytest==6.0.1
pytest-asyncio==0.14.0
pytest-cov==2.10.1
pytest-benchmark==3.2.3
pytest-django==3.9.0
pytest-flake8==1.0.6
pytest-mock==3.2.0
pytest-xdist==2.0.0
pytest-bdd==3.4.0
python:3.8.5-alpine3.12
Django 3.1

Upgraded pytest-xdist from 1.34.0 to 2.0.0

**Comment by tolomea** [comment]
Same thing here, also failing on mysql but with a different error.
Both errors kinda imply that per thread test db naming has broken, so all the threads are sharing a single db.
In the interim you can work around it by forcing single threaded or pinning pytest-xdist<2.0

**Comment by tolomea** [comment]
The mysql error is ```MySQLdb._exceptions.OperationalError: (1050, "Table 'django_migrations' already exists")```
