### ISSUE TITLE
Release 3.10.0

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest-django#863]
There are some compat fixes which would be nice to get out:

- Fix for pytest-xdist 2
- Fix for pytest 6 (internal pytest-django tests only)
- Fix for Django 3.2

I have never made a release here before, but if I understand correctly, all that's needed is to push a changelog update and tag it, and it is published automatically using @blueyed's PyPI token.

I will do it in a few days, unless someone objects (or volunteers).

**Comment by bluetech** [comment]
Well I tried but it seems like the token is not valid anymore:

```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
```

(See job: https://travis-ci.org/github/pytest-dev/pytest-django/jobs/721042875).

So now it's a bit of a mess with the release committed and tagged but not published to PyPI...

@blueyed and @pelme: according to https://pypi.org/project/pytest-django/ you are the users who have permission to publish to PyPI. Do you think you could manually publish the wheel, or update the travis token maybe? Sorry for the mess, I hoped it would work.

**Comment by mgorny** [comment]
@bluetech if you're using `setup.py upload`, then try `twine upload` instead. It seems that the former was broken recently, at least for my projects.

**Comment by bluetech** [comment]
It is using this:

https://github.com/pytest-dev/pytest-django/blob/7474f9bee92979f5a53d92544e8f5a7cf1de67b7/.travis.yml#L72-L83

**Comment by mgorny** [comment]
I'm sorry, I can't help you with that.

**Comment by D3X** [comment]
@bluetech @pelme any chance you could help with getting this released?

**Comment by nicoddemus** [comment]
(From https://github.com/pytest-dev/pytest/issues/7585#issuecomment-691510957):

@pelme could you add me and/or @bluetech as publishers on PyPI? We can take it from there (my username is also `nicoddemus`). @bluetech what's yours?

**Comment by pelme** [comment]
Sorry for the delay. I have added @nicoddemus as owner on PyPI now. I did not know @bluetech 's PyPI username but please reply here and I will add you too!

Thank you 🙏  and let me know if I can be of any other help.

**Comment by bluetech** [comment]
@pelme Great, thanks!

My PyPI username is `bluetech` (just created actually). Once added, I'll complete this release.

**Comment by pelme** [comment]
@bluetech Awesome! You are now invited on PyPI.

**Comment by bluetech** [comment]
3.10.0 is released to PyPI now.

---

Note I made the upload locally; I tried to update the token in the travis file but when trying to encrypt the new token it gives some error about the token being too long... Will find some time to investigate before the next release though. Maybe just switch to github actions?

**Comment by D3X** [comment]
> Maybe just switch to github actions?

Sounds like a good idea. You can then store the keys in github's secret store.
