### ISSUE TITLE
Fixture for Async Client

### ISSUE THREAD

**Issue by ResleyR** [pytest-dev/pytest-django#864]
With Django 3.1 it would be useful to have an `async_client` fixture similar to the existing `client` fixture.          
 The following code works but would be nice if it was part the plugin itself

```python
@pytest.fixture()
def async_client():
    """A Django async test client instance."""
    skip_if_no_django()

    if get_django_version() < (3, 1):
        pytest.skip("no Django settings")
    from django.test.client import AsyncClient

    return AsyncClient()
```

This allows for testing async views when used along with [pytest-asyncio](https://pypi.org/project/pytest-asyncio/) with the alternative being using the django TestCase instead.

**Comment by bluetech** [comment]
Fixed in #865, will be in 4.1 (along with `async_rf`).

The fixture as written doesn't do the automatic `pytest.skip` on django<3.1. Personally not sure automatic skip is a good idea...
