### ISSUE TITLE
Tests on master are failing with pytest 6.1.1

### ISSUE THREAD

**Issue by michael-k** [pytest-dev/pytest-django#875]
I've noticed that the baseline tests on master are currently failing.  They pass when pytest is pinned to `<6.1`.  Logs are available here:
- fail: https://travis-ci.com/github/michael-k/pytest-django/builds/188604675
- pass: https://travis-ci.com/github/michael-k/pytest-django/builds/188608938

They are failing because `'* 1 passed in*'` does not match `======================== 1 passed, 2 warnings in 0.05s =========================`.  The change in the handling of internal warnings in pytest 6.1.0 might be the causing this, but I didn't investigate this further yet (changelog: https://docs.pytest.org/en/stable/changelog.html#improvements).

**Comment by michael-k** [comment]
> Need to find where it's coming from (not from pytest-django itself at least).

Might be also coming from django-configurations, see jazzband/django-configurations#263

**Comment by michael-k** [comment]
I've opened PR jazzband/django-configurations#264 that drops support for Python 2 and should make it possible to switch from `imp` to `importlib`, but I haven't figured out how to do that.

**Comment by bluetech** [comment]
For now I have a fix for this as part of #876 -- just making the tests less sensitive to whether there are warnings are not. I figure we don't want to fail whenever a new one comes up. I also noticed some warnings from mysql libraries.
