### ISSUE TITLE
RuntimeError: Settings already configured

### ISSUE THREAD

**Issue by minusf** [pytest-dev/pytest-django#887]
The documentation says it's possible to set django settings using this simple setup:

https://pytest-django.readthedocs.io/en/latest/configuring_django.html#using-django-conf-settings-configure

I am trying to override caching to use the dummy backend and i get:

```py
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}

def pytest_configure():
    settings.configure(CACHES=CACHES)
```

```
ERROR  - RuntimeError: Settings already configured.
```

From the wording it's not clear to me if "set up" includes overriding as well, but setting non-existent variables results in the same error.

**Comment by minusf** [comment]
right this worked:

```py
def pytest_configure():
    settings.CACHES = CACHES
```

**Comment by minusf** [comment]
is the documentation out of date or i made a boo boo? :}

**Comment by bluetech** [comment]
`settings.configure` is a way to specify complete settings without a settings.py/DJANGO_SETTINGS_MODULE, see [here](https://docs.djangoproject.com/en/3.1/topics/settings/#using-settings-without-setting-django-settings-module). From your use case it is *probably* not what you want.

Some alternatives are:

1. Make your settings themselves conditional (like on DEBUG or an environment variable) such that the tests use the dummy backend.

2. Use the [`settings`](https://pytest-django.readthedocs.io/en/latest/helpers.html#settings) fixture and an autouse fixture to automatically change the setting in the setup of each test:
```py
import pytest

@pytest.fixture(autouse=True)
def use_dummy_cache_backend(settings):
    settings.CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
```

You can put this in a `conftest.py` file in your root tests directory for example.

Good luck :)

**Comment by minusf** [comment]
that's a great explanation in that link, perhaps it could be added somehow to the documentation to make it a bit more explicit?

so you wouldnt recommend the `pytest_configure` approach at all?  it seemed to work similarly as the `autouse` fixture:

```
def pytest_configure():
    settings.CACHES = CACHES
```

**Comment by bluetech** [comment]
Using the `pytest_configure` is OK but it overrides the global Django setting in an uncontrolled manner and does not restore it afterward the test session is finished. If that's fine for you and you're not doing anything fancy, then you can do it this way.

**Comment by minusf** [comment]
would you be interested in #890 ?

**Comment by minusf** [comment]
please close :}
