### ISSUE TITLE
django_user_model in every test method

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [pytest-dev/pytest-django#891]
This is a question rather than issue...

Is it possible to have 'django_user_model' fixture availible in each and every test method in project's tests by default without explicitly adding it in each test method llke:
`def test_x(django_user_model, )`

I have 550 tests in a project and would like to not add it in each one individually.

Thank you for the great package by the way.

**Comment by symonk** [comment]
Hi @AlekseiKhatkevich I'm not too familiar with pytest-django (or django in general - just pytest core), this exists, but obviously the yield/return values wouldn't be available (easily - perhaps through some tricks)

```
[pytest]
usefixtures = django_user_model
```
