### ISSUE TITLE
running all tests with --fail-on-template-vars pass but running a single test with an undefined template var fails

### ISSUE THREAD

**Issue by BielStela** [pytest-dev/pytest-django#901]
Hello,
I'm dealing with a confusing issue. I have`--fail-on-template-vars` in my pytest.ini. When I run all the tests, all tests pass. But I know there are some test that should fail because they have undefined template vars. When I do a single run on the tests that should fail with `-k` they fail. After that if I run again the full test suit the error is noticed and the test fail. 
So resuming:
1. Run all tests: **Pass**
2. Run single test that should fail: **Fail**
3. Run all tests: **Fail**

I can't figure out what's going on.
I'm using pytest 6.3.1 and pytest-django 4.1.0

Thank you!

**Comment by bluetech** [comment]
Can you provide a way to reproduce this?

**Comment by bluetech** [comment]
Possibly fixed by 4e1906ad88c2cc101d158e6b6de910992b96ddd5, let me know if not.
