### ISSUE TITLE
Issue with Model Import Paths

### ISSUE THREAD

**Issue by jpulec** [pytest-dev/pytest-django#907]
It seems that pytest-django doesn't quite work properly if models are structured in a certain way.

For example, if your app has the following structure:

```shell
- project/
-   apps/
-     core/
-     users/
-       models/
-         user.py
```

In the above case, pytest-django will fail, because it will try to import `user.py` as `users.models.user`, which will not match the full path django expects when trying to create the model and look it up in the registry using the function `apps.get_containing_app_config(module)`. Django uses the `AppConfig.name` field for these lookups, which are are supposed to be full paths, i.e. `project.apps.users.user` in this case.

**Comment by bluetech** [comment]
Hi @jpulec, can you show the concrete error, the concrete paths (e.g. I assume there are some `__init__.py`s in there), the relevant `AppConfig` and the pytest command you use? That would save some time in investigating the issue.

**Comment by jpulec** [comment]
@bluetech Wow. Thank you for getting back to me and throwing me that hint around `__init__.py` files. I was missing one in hierarchy of my folders, which appears to have caused the issued. Once I added it, everything starting working smoothly.

I appreciate the help and sorry to raise a false report here. Gonna close this out.
