### ISSUE TITLE
docs(readme): update readme broken-links.

### ISSUE THREAD

**Issue by wearypossum4770** [pytest-dev/pytest-django#914]
- line 58
 -  Manage test dependencies with pytest fixtures. <https://pytest.org/en/latest/fixture.html>
- line 62 
 - Make use of other `pytest plugins <https://pytest.org/en/latest/plugins.html>

Will submit a pull request for this.

**Comment by bluetech** [comment]
Hi @wearypossum4770, your commit looks good to me, if you want to submit it :)
