### ISSUE TITLE
asserts module cannot import name 'assertDictEqual' and other TestCase assertion methods

### ISSUE THREAD

**Issue by MohamedAbdultawab** [pytest-dev/pytest-django#939]
Trying to get assertDictEqual from pytest_django.asserts with multiple ways:
`from pytest_django.asserts import assertDictEqual
`
or 
`from pytest_django import asserts`
both of them throws errors
the first one's error:

>     from pytest_django.asserts import assertDictEqual
> E   ImportError: cannot import name 'assertDictEqual' from 'pytest_django.asserts' (/usr/local/lib/python3.7/site-packages/pytest_django/asserts.py)

the second one's error:

> AttributeError: module 'pytest_django.asserts' has no attribute 'assertDictEqual'

**Comment by bluetech** [comment]
`assertDictEqual ` is not a Django assertion so is not included. For dicts it's better to use pytest's builtin support for plain asserts e.g. `assert my_dict == {"a": "b"}`.
