### ISSUE TITLE
Add support for latest stable Python and Django versions

### ISSUE THREAD

**Issue by pauloxnet** [pytest-dev/pytest-django#965]

**Comment by hramezani** [comment]
We already have Python 3.10 in our test matrix https://github.com/pytest-dev/pytest-django/commit/ac76775fa0a931307eb5f90cee11e4c6cf4aebb8
Also, the master supports Django main https://github.com/pytest-dev/pytest-django/commit/c5465adbf6fa9cde4a00d3cacc2246d575430b54

@bluetech will make a release for this changes

**Comment by pauloxnet** [comment]
I think we can add Django 4.0rc1in the test matrix.

**Comment by bluetech** [comment]
It's done now.
