### ISSUE TITLE
Support for SimpleTestCase.assertTemplateUsed etc

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-django#97]
I wonder if there is currently a way to use e.g. methods like [assertTemplateUsed](https://docs.djangoproject.com/en/dev/topics/testing/tools/#django.test.SimpleTestCase.assertTemplateUsed) from Django's SimpleTestCase with pytest-django directly.

I know that I could use a standard SimpleTestCase, but maybe I am just missing something.
What would be the approach to get things like this into pytest-django, if this would be desired?

**Comment by bittner** [comment]
I've tried to make PR #144 work opening the new PR #232, where I also merged in the current `master` to resolve merge conflicts in the PR.

Currently, the code doesn't seem to provide the `assertXxx` boilerplate functions via simple `assert` statements ([see what Travis-CI reports](https://travis-ci.org/pytest-dev/pytest-django/jobs/58845538)). Can you guys help me understand what needs to be changed? -- How is this done in py.test? (I've not yet understood how the `assert` magic is done.)

I'm wondering whether the code in the original PR ever worked. GitHub reports it did (via Travis-CI integration), but the related test runs don't exist on Travis-CI.  :worried:

**Comment by blueyed** [comment]
@bittner 
The last build of #144 is: https://travis-ci.org/pytest-dev/pytest-django/builds/31046637 (you need to fix the URL, the repo has been renamed).

**Comment by blueyed** [comment]
Closing this in favor of #232 (which is a continuation of this one).
