### ISSUE TITLE
4.5.1: reset_sequences=True fails on MariaDB/MySQL

### ISSUE THREAD

**Issue by joaquimds** [pytest-dev/pytest-django#978]
Firstly, thanks for maintaining such a powerful and useful testing library for Django.

On to the bug:

- OS: Windows 10
- Python: 3.9.1
- pytest-6.2.5
- py-1.11.0
- pluggy-1.0.0
- Django: 3.2.10

Example:

    @pytest.mark.django_db(reset_sequences=True)
    def test_reset_sequences():
        assert True

Output:

    ERROR my_test.py::test_reset_sequences - AssertionError: reset_sequences cannot be used on TestCase instances

**Comment by bluetech** [comment]
It's missing `transaction=True`. Needs a better error message.

Did it work on pytest-django 4.4.0? If yes, then I'll make it work again.
