### ISSUE TITLE
Cannot import from pytest_django.assert.

### ISSUE THREAD

**Issue by NaughtyGnosiophile** [pytest-dev/pytest-django#982]
I keep getting this error:

```
 from pytest_django.asserts import assertEqual
E   ImportError: cannot import name 'assertEqual' from 'pytest_django.asserts' (
/home/cdev/.local/lib/python3.8/site-packages/pytest_django/asserts.py)
```

This is what my file looks like:
```
import pytest

from pytest_django.asserts import assertEqual

from eclp.dragons.models import Supplier


@pytest.mark.usefixtures("address")
@pytest.mark.django_db
def test_supplier_create(address):
    supplier = Supplier.objects.create(
        name="name",
        description="description",
        contact="contact",
        address=address,
    )


    assertEqual(supplier.name, "name")
```

I can do this though:
```
from pytest_django.assert import test_case

test_case.assertEqual()
```
But that's not very nice.
Any ideas?

pytest_django 3.9.0
django 2.2.19

**Comment by hramezani** [comment]
In [django pytest assertion documentation](https://pytest-django.readthedocs.io/en/latest/helpers.html#assertions) we have:

> All of Django’s TestCase Assertions are available in pytest_django.asserts, e.g.
 
But `assertEqual` is a Python [unittest.TestCase](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertEqual) method.
