### ISSUE TITLE
pytest-pythonpath is no longer compatible with pytest 7

### ISSUE THREAD

**Issue by mellobet** [pytest-dev/pytest-django#990]
# pytest-pythonpath is no longer compatible with pytest 7

It should be removed or mentioned from/in docs [here].
[This] should be used instead.

[here]: <https://pytest-django.readthedocs.io/en/latest/managing_python_path.html#using-pytest-pythonpath>
[This]: <https://docs.pytest.org/en/7.0.x/reference/reference.html#confval-pythonpath>

**Comment by bluetech** [comment]
This will be fixed in pytest 7.0.1 (not released yet).
