### ISSUE TITLE
Question: How to run tests under selected tag just like django.test.TestCase with tag

### ISSUE THREAD

**Issue by edchelstephens** [pytest-dev/pytest-django#994]
Is there an implementation for this in pytest-django?

Thanks a lot!

**Comment by hramezani** [comment]
Have you looked at https://github.com/pytest-dev/pytest-django/issues/818?

**Comment by edchelstephens** [comment]
I think this answed it for me. Thanks!

https://docs.pytest.org/en/6.2.x/example/markers.html

**Comment by edchelstephens** [comment]
> Have you looked at #818?

I think this answed it for me. Thanks!

https://docs.pytest.org/en/6.2.x/example/markers.html
